Repository radicle-dev/radicle-upstream, pull requests merged in 2020-12, with the labels that each got.

#1434 fix(ui): open only one modal at a time
  ui/Hotkeys.svelte
Labels: improvement, ui

#1436 feat(ui): extend effect of enter key in onboarding
  ui/Screen/Onboarding/EnterName.svelte
  ui/Screen/Onboarding/EnterPassphrase.svelte
Labels: improvement, ui

#1450 fix(ui): revert to default after untrack
  ui/src/screen/project.ts
Labels: bug, ui

#1452 docs: link to repositories that have to be updated upon release
  DEVELOPMENT.md
Labels: improvement

#1459 package.json: mark git deps with a git+
  package.json
  yarn.lock
Labels: improvement, infrastructure

#1474 fix(ci): put timeout on proxy tests
  .buildkite/run.sh
Labels: improvement, infrastructure

#1467 fix(ui): list border overflow (#1447)
  ui/DesignSystem/Component/List.svelte
Labels: improvement, ui
