Repository radicle-dev/radicle-upstream, pull requests merged in 2020-04, with the labels that each got.

#264 Adjust project creation UX according to new designs
  cypress/integration/project_creation.spec.js
  cypress/support/commands.js
  proxy/src/coco.rs
  proxy/src/graphql/schema.rs
  proxy/src/project.rs
  proxy/tests/common/mod.rs
  proxy/tests/graphql_mutation.rs
  proxy/tests/graphql_query.rs
  ui/DesignSystem/Component/ProjectList.svelte
  ui/DesignSystem/Primitive/Input/Text.svelte
  ui/Screen/CreateProject.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/Source.svelte
Labels: improvement, ui

#242 Implement transaction center
  cypress/integration/user_registration.spec.js
  native/types.js
  proxy/src/graphql/schema.rs
  proxy/tests/graphql_query.rs
  ui/App.svelte
  ui/DesignSystem/Component/SidebarLayout.svelte
  ui/DesignSystem/Component/Transaction.svelte
  ui/DesignSystem/Component/Transaction/Accordion.svelte
  ui/DesignSystem/Component/Transaction/Center.svelte
  ui/DesignSystem/Component/Transaction/Statusbar.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Icon/Expand.svelte
  ui/DesignSystem/Primitive/Icon/TransactionState.svelte
  ui/DesignSystem/Primitive/Icon/index.js
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/RegisterProject.svelte
  ui/Screen/RegisterProject/ConfirmTransactionStep.svelte
  ui/Screen/RegisterProject/TransactionSummaryStep.svelte
  ui/Screen/TransactionDetails.svelte
  ui/Screen/UserRegistration.svelte
  ui/Screen/UserRegistration/PickHandleStep.svelte
  ui/Screen/UserRegistration/SubmitRegistrationStep.svelte
  ui/lib/hotkeys.js
  ui/lib/path.js
Labels: feature, ui

#276 Remove avatar fallback query from user registration
  ui/Screen/UserRegistration.svelte
  ui/Screen/UserRegistration/PickHandleStep.svelte
  ui/Screen/UserRegistration/SubmitRegistrationStep.svelte
Labels: improvement, ui

#278 feat: single commit view header
  proxy/src/coco.rs
  proxy/src/graphql/schema.rs
  proxy/src/lib.rs
  ui/DesignSystem/Component/SourceBrowser/CommitTeaser.svelte
  ui/DesignSystem/Component/SourceBrowser/FileList.svelte
  ui/DesignSystem/Component/SourceBrowser/FileSource.svelte
  ui/DesignSystem/Primitive/Code.svelte
  ui/DesignSystem/Primitive/Title.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/Commit.svelte
  ui/lib/path.js
Labels: feature, ui

#266 feat: fetch identity on app boot
  DEVELOPMENT.md
  cypress/integration/identity_creation.spec.js
  cypress/integration/project_creation.spec.js
  cypress/integration/source_browsing.spec.js
  cypress/integration/user_registration.spec.js
  cypress/support/commands.js
  cypress/support/index.js
  native/main.js
  package.json
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/error.rs
  proxy/src/graphql.rs
  proxy/src/graphql/api.rs
  proxy/src/graphql/error.rs
  proxy/src/graphql/schema.rs
  proxy/src/identity.rs
  proxy/src/lib.rs
  proxy/src/main.rs
  proxy/src/session.rs
  proxy/tests/common/mod.rs
  proxy/tests/graphql_control_mutation.rs
  proxy/tests/graphql_mutation.rs
  proxy/tests/graphql_query.rs
  public/index.html
  public/typography.css
  ui/App.svelte
  ui/DesignSystem/Component/ProjectList.svelte
  ui/Screen/Blank.svelte
  ui/Screen/Identity/IdentityCreationSuccess.svelte
  ui/Screen/IdentityCreation.svelte
  ui/lib/hotkeys.js
  yarn.lock
Labels: feature, ui

#299 Fix stacking of dropdowns
  package.json
  ui/DesignSystem/Component/AdditionalActionsDropdown.svelte
  ui/DesignSystem/Component/Topbar.svelte
  yarn.lock
Labels: bug, ui

#300 feat(proxy): org API endpoints
  proxy/src/http.rs
  proxy/src/http/org.rs
  proxy/src/registry.rs
Labels: feature, proxy

#296 feat: source browsing in the new API
  package.json
  proxy/Cargo.lock
  proxy/src/coco.rs
  proxy/src/graphql/schema.rs
  proxy/src/http.rs
  proxy/src/http/error.rs
  proxy/src/http/project.rs
  proxy/src/http/source.rs
  proxy/tests/graphql_query.rs
  tsconfig.json
  ui/DesignSystem/Component/SourceBrowser.svelte
  ui/DesignSystem/Component/SourceBrowser/File.svelte
  ui/DesignSystem/Component/SourceBrowser/FileList.svelte
  ui/DesignSystem/Component/SourceBrowser/FileSource.svelte
  ui/DesignSystem/Component/SourceBrowser/Folder.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Input/Dropdown.svelte
  ui/Screen/CreateProject.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/Commit.svelte
  ui/Screen/Project/Source.svelte
  ui/lib/path.js
  ui/src/api.ts
  ui/src/avatar.ts
  ui/src/project.ts
  ui/src/source.ts
  ui/store/sourceBrowser.js
  yarn.lock
Labels: improvement, proxy, ui

#298 feat(ui): commit changeset UI
  ui/DesignSystem/Component/SourceBrowser/FileDiff.svelte
  ui/Screen/Project/Commit.svelte
  ui/lib/commitMocks.ts
  ui/src/source.ts
Labels: feature, ui

#305 feat: transactions through REST API
  proxy/src/http/transaction.rs
  ui/DesignSystem/Component/Transaction.svelte
  ui/DesignSystem/Component/Transaction/Center.svelte
  ui/Screen/RegisterProject/ConfirmTransactionStep.svelte
  ui/Screen/TransactionDetails.svelte
  ui/Screen/UserRegistration/SubmitRegistrationStep.svelte
  ui/src/transaction.ts
Labels: feature, proxy, ui

#294 feat(ui): new project page with repository selector
  cypress/integration/source_browsing.spec.js
  proxy/src/coco.rs
  proxy/src/http/source.rs
  proxy/src/identity.rs
  ui/DesignSystem/Component/SourceBrowser/CommitTeaser.svelte
  ui/DesignSystem/Component/SourceBrowser/File.svelte
  ui/DesignSystem/Component/SourceBrowser/FileSource.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/DesignSystem/Component/Stat.svelte
  ui/DesignSystem/Primitive/Avatar.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/Commit.svelte
  ui/Screen/Project/Source.svelte
  ui/src/source.ts
Labels: feature, ui

#301 fix(ui): restyle notification banners
  ui/DesignSystem/Component/Notification.svelte
  ui/DesignSystem/Component/NotificationFaucet.svelte
  ui/DesignSystem/Primitive/Icon/Important.svelte
  ui/Screen/DesignSystemGuide.svelte
Labels: improvement, ui

#310 refactor(ui): remote component
  ui/DesignSystem/Component/ProjectList.svelte
  ui/DesignSystem/Component/Remote.svelte
  ui/DesignSystem/Component/Sidebar.svelte
  ui/DesignSystem/Component/SourceBrowser/Folder.svelte
  ui/DesignSystem/Component/Transaction/Center.svelte
  ui/DesignSystem/Component/index.js
  ui/Screen/Identity/IdentityCreationSuccess.svelte
  ui/Screen/Profile.svelte
  ui/Screen/Profile/Onboard.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/Commit.svelte
  ui/Screen/Project/Source.svelte
  ui/Screen/TransactionDetails.svelte
  ui/lib/path.js
  ui/src/transaction.ts
Labels: improvement, ui

#314 fix(ui): timely session fetch
  ui/Screen/Identity/IdentityCreationSuccess.svelte
  ui/Screen/IdentityCreation.svelte
Labels: bug, ui

#312 refactor: Migrate outstanding endpoints to REST
  DEVELOPMENT.md
  cypress/support/commands.js
  graphiql/index.html
  package.json
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/README.md
  proxy/src/graphql.rs
  proxy/src/graphql/api.rs
  proxy/src/graphql/error.rs
  proxy/src/graphql/schema.rs
  proxy/src/http.rs
  proxy/src/http/control.rs
  proxy/src/http/doc.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/source.rs
  proxy/src/http/user.rs
  proxy/src/lib.rs
  proxy/src/main.rs
  proxy/src/registry.rs
  proxy/tests/common/mod.rs
  proxy/tests/graphql_control_mutation.rs
  proxy/tests/graphql_mutation.rs
  proxy/tests/graphql_query.rs
  ui/App.svelte
  ui/Screen/CreateProject.svelte
  ui/Screen/Network.svelte
  ui/Screen/RegisterProject.svelte
  ui/Screen/UserRegistration.svelte
  ui/Screen/UserRegistration/PickHandleStep.svelte
  ui/src/project.ts
  ui/src/user.ts
  yarn.lock
Labels: improvement, proxy, ui

#318 fix(ui): remove graphiql from start script
  package.json
Labels: bug, ui

#319 fix(ui): project creation
  ui/Screen/CreateProject.svelte
  ui/src/project.ts
Labels: bug, ui

#309 feat(proxy): list all orgs by member
  proxy/src/http/identity.rs
  proxy/src/http/notification.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/session.rs
  proxy/src/http/source.rs
  proxy/src/http/transaction.rs
  proxy/src/http/user.rs
  proxy/src/registry.rs
Labels: feature, proxy

#311 feat(ui): finalize design on project source view
  cypress/integration/source_browsing.spec.js
  ui/DesignSystem/Component/SourceBrowser/CommitTeaser.svelte
  ui/DesignSystem/Component/SourceBrowser/File.svelte
  ui/DesignSystem/Component/SourceBrowser/FileList.svelte
  ui/DesignSystem/Component/SourceBrowser/FileSource.svelte
  ui/DesignSystem/Component/SourceBrowser/Folder.svelte
  ui/DesignSystem/Component/SourceBrowser/Readme.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/Screen/Project/Commit.svelte
  ui/Screen/Project/Source.svelte
  ui/src/source.ts
Labels: ui

#326 chore(ui): design cleanup
  ui/DesignSystem/Component/Transaction/Accordion.svelte
  ui/DesignSystem/Component/Transaction/Statusbar.svelte
  ui/DesignSystem/Primitive/Button.svelte
  ui/Screen/CreateProject.svelte
  ui/Screen/DesignSystemGuide.svelte
Labels: improvement, ui

#325 feat(ui): implement tracking button
  ui/DesignSystem/Component/TrackToggle.svelte
Labels: improvement, ui

#322 feat: fetch registered project
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/error.rs
  proxy/src/http.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/session.rs
  proxy/src/http/transaction.rs
  proxy/src/http/user.rs
  proxy/src/identity.rs
  proxy/src/lib.rs
  proxy/src/project.rs
  proxy/src/registry.rs
  proxy/src/session.rs
  ui/src/project.ts
  ui/src/user.ts
Labels: feature, proxy, ui

#328 chore(ui): fix button
  ui/DesignSystem/Primitive/Button.svelte
Labels: ui

#329 feat(ui): implement 'Clone' button
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/Screen/Project/CloneButton.svelte
  ui/Screen/Project/Source.svelte
Labels: feature, ui
