Repository radicle-dev/radicle-upstream, pull requests merged in 2020-05, with the labels that each got.

#280 feat(ui): org registration
  ui/App.svelte
  ui/DesignSystem/Component/IdentityAvatar.svelte
  ui/DesignSystem/Component/Registration/NavigationButtons.svelte
  ui/DesignSystem/Component/Sidebar.svelte
  ui/DesignSystem/Component/SourceBrowser/Readme.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/DesignSystem/Component/Transaction.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Avatar.svelte
  ui/DesignSystem/Primitive/Input/Directory.svelte
  ui/DesignSystem/Primitive/Input/Text.svelte
  ui/Screen/CreateProject.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Identity/IdentityCreationForm.svelte
  ui/Screen/Org.svelte
  ui/Screen/OrgRegistration.svelte
  ui/Screen/Project/Breadcrumb.svelte
  ui/Screen/RegisterProject/PickNameStep.svelte
  ui/Screen/RegisterProject/PickWalletStep.svelte
  ui/Screen/UserRegistration/PickHandleStep.svelte
  ui/lib/hotkeys.js
  ui/lib/path.js
  ui/src/org.ts
  ui/src/validation.ts
Labels: feature, ui

#292 feat(ui): project registration flow
  cypress/integration/project_creation.spec.js
  cypress/integration/user_registration.spec.js
  proxy/src/identity.rs
  public/elevation.css
  public/global.css
  public/index.html
  ui/App.svelte
  ui/DesignSystem/Component/AdditionalActionsDropdown.svelte
  ui/DesignSystem/Component/Copyable.svelte
  ui/DesignSystem/Component/Dropdown.svelte
  ui/DesignSystem/Component/Dropdown/Option.svelte
  ui/DesignSystem/Component/IdentityAvatar.svelte
  ui/DesignSystem/Component/ModalLayout.svelte
  ui/DesignSystem/Component/ProjectCard.svelte
  ui/DesignSystem/Component/ProjectList.svelte
  ui/DesignSystem/Component/Sidebar.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/DesignSystem/Component/StepCounter.svelte
  ui/DesignSystem/Component/Topbar.svelte
  ui/DesignSystem/Component/Transaction.svelte
  ui/DesignSystem/Component/Transaction/Accordion.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Avatar.svelte
  ui/DesignSystem/Primitive/Flex.svelte
  ui/DesignSystem/Primitive/Icon/StepCounter.svelte
  ui/DesignSystem/Primitive/Input/Text.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Org.svelte
  ui/Screen/Org/ProjectsMenu.svelte
  ui/Screen/Profile.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Project.svelte
  ui/Screen/ProjectRegistration.svelte
  ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
  ui/Screen/RegisterProject.svelte
  ui/Screen/RegisterProject/ConfirmTransactionStep.svelte
  ui/Screen/RegisterProject/PickNameStep.svelte
  ui/Screen/RegisterProject/PickWalletStep.svelte
  ui/Screen/UserRegistration/PickHandleStep.svelte
  ui/lib/path.js
  ui/src/project.ts
  ui/src/transaction.ts
  ui/store/identity.js
Labels: feature, ui

#331 style(ui): project page facelift
  ui/DesignSystem/Component/SourceBrowser/CommitTeaser.svelte
  ui/DesignSystem/Component/SourceBrowser/FileDiff.svelte
  ui/DesignSystem/Component/SourceBrowser/FileSource.svelte
  ui/DesignSystem/Component/SourceBrowser/Readme.svelte
  ui/Screen/Project/CloneButton.svelte
  ui/Screen/Project/Commit.svelte
  ui/Screen/Project/Source.svelte
Labels: improvement, ui

#336 fix: correct attestion field name in user
  proxy/src/http/user.rs
  proxy/src/registry.rs
  ui/src/user.ts
Labels: bug, proxy, ui

#341 feat: expose current user orgs list in session
  proxy/src/http.rs
  proxy/src/http/identity.rs
  proxy/src/http/session.rs
  proxy/src/registry.rs
  proxy/src/session.rs
  ui/App.svelte
  ui/Screen/Profile.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Project.svelte
  ui/Screen/ProjectRegistration.svelte
  ui/Screen/TransactionDetails.svelte
  ui/Screen/UserRegistration.svelte
  ui/src/org.ts
  ui/src/session.ts
Labels: feature, proxy, ui

#333 feat(ui): org registration flow api integration
  ui/DesignSystem/Component/Transaction.svelte
  ui/Screen/OrgRegistration.svelte
  ui/src/avatar.ts
  ui/src/org.ts
  ui/src/transaction.ts
  ui/src/validation.ts
Labels: feature, ui

#337 feat(ui): commit history view
  proxy/src/coco.rs
  proxy/src/http/source.rs
  ui/DesignSystem/Component/SourceBrowser/CommitTeaser.svelte
  ui/DesignSystem/Component/UserCard.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/Commits.svelte
  ui/Screen/Project/Source.svelte
  ui/lib/path.js
  ui/src/source.ts
Labels: feature, proxy, ui

#339 feat(ui): use Twitter svg emojis in Avatar component
  .gitignore
  README.md
  package.json
  public/twemoji/.gitkeep
  ui/DesignSystem/Primitive/Avatar.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/DesignSystemGuide/Swatch.svelte
  yarn.lock
Labels: improvement, ui

#345 feat(ui): wire up orgs
  ui/DesignSystem/Component/Sidebar.svelte
  ui/DesignSystem/Component/SidebarLayout.svelte
  ui/Screen/Org.svelte
  ui/Screen/OrgRegistration.svelte
  ui/Screen/ProjectRegistration.svelte
  ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
  ui/src/org.ts
Labels: feature, ui

#330 feat(proxy): add avatar endpoint
  proxy/src/http.rs
  proxy/src/http/avatar.rs
  proxy/src/http/error.rs
Labels: feature, proxy

#352 chore(ui): upgrade all UI dependencies
  cypress/integration/routing.spec.js
  cypress/integration/source_browsing.spec.js
  cypress/support/commands.js
  native/ipc.js
  native/main.js
  native/preload.js
  package.json
  rollup.app.js
  rollup.electron.js
  scripts/generate-colors.js
  tokens/colors.js
  ui/App.svelte
  ui/DesignSystem/Component/AdditionalActionsDropdown.svelte
  ui/DesignSystem/Component/Dropdown.svelte
  ui/DesignSystem/Component/NotificationFaucet.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/DesignSystem/Component/Transaction.svelte
  ui/DesignSystem/Component/Transaction/Accordion.svelte
  ui/DesignSystem/Component/Transaction/Statusbar.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Avatar.svelte
  ui/DesignSystem/Primitive/Icon/TransactionState.svelte
  ui/DesignSystem/Primitive/Icon/index.js
  ui/DesignSystem/Primitive/Input/index.js
  ui/DesignSystem/Primitive/index.js
  ui/Screen/CreateProject.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Identity/IdentityCreationForm.svelte
  ui/Screen/Identity/IdentityCreationSuccess.svelte
  ui/Screen/IdentityCreation.svelte
  ui/Screen/Org.svelte
  ui/Screen/OrgRegistration.svelte
  ui/Screen/Profile.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/CloneButton.svelte
  ui/Screen/Project/Commit.svelte
  ui/Screen/Project/Commits.svelte
  ui/Screen/Project/Source.svelte
  ui/Screen/ProjectRegistration.svelte
  ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
  ui/Screen/TransactionDetails.svelte
  ui/Screen/UserRegistration.svelte
  ui/Screen/UserRegistration/PickHandleStep.svelte
  ui/Screen/UserRegistration/SubmitRegistrationStep.svelte
  ui/index.js
  ui/lib/hash.js
  ui/lib/hotkeys.js
  ui/lib/orgMocks.js
  ui/lib/path.js
  ui/src/org.ts
  ui/src/transaction.ts
  ui/src/validation.ts
  ui/store/notification.js
  yarn.lock
Labels: improvement, ui

#354 fix(ui): identity creation regression
  ui/Screen/Identity/IdentityCreationForm.svelte
  ui/Screen/Identity/IdentityCreationSuccess.svelte
  ui/Screen/IdentityCreation.svelte
  ui/src/identity.ts
  ui/src/onboard.ts
Labels: bug, ui

#343 feat(proxy): org project list endpoint
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/registry.rs
Labels: feature, proxy

#359 test(ui): improve identity creation test coverage
  cypress/integration/identity_creation.spec.js
  ui/DesignSystem/Component/ModalLayout.svelte
  ui/DesignSystem/Primitive/Avatar.svelte
  ui/Screen/Identity/IdentityCreationForm.svelte
  ui/Screen/Identity/IdentityCreationSuccess.svelte
  ui/Screen/IdentityCreation.svelte
  ui/Screen/Profile.svelte
Labels: bug, ui

#357 refactor(ui): consolidate to ts
  .gitignore
  native/ipc.js
  native/main.js
  native/types.js
  tsconfig.json
  ui/App.svelte
  ui/DesignSystem/Component/HorizontalMenu.svelte
  ui/DesignSystem/Component/ModalLayout.svelte
  ui/DesignSystem/Component/Notification.svelte
  ui/DesignSystem/Component/NotificationFaucet.svelte
  ui/DesignSystem/Component/Sidebar.svelte
  ui/DesignSystem/Component/SidebarLayout.svelte
  ui/DesignSystem/Component/SourceBrowser/CommitTeaser.svelte
  ui/DesignSystem/Component/SourceBrowser/File.svelte
  ui/DesignSystem/Component/SourceBrowser/Folder.svelte
  ui/DesignSystem/Component/Transaction/Accordion.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/IdentityCreation.svelte
  ui/Screen/IdentityCreation/Form.svelte
  ui/Screen/IdentityCreation/Success.svelte
  ui/Screen/Org.svelte
  ui/Screen/Org/ProjectsMenu.svelte
  ui/Screen/OrgRegistration.svelte
  ui/Screen/Profile.svelte
  ui/Screen/Profile/Onboard.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Profile/ProjectsMenu.svelte
  ui/Screen/Profile/SettingsMenu.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/Commit.svelte
  ui/Screen/Project/Commits.svelte
  ui/Screen/Project/Source.svelte
  ui/Screen/ProjectCreation.svelte
  ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
  ui/Screen/UserRegistration.svelte
  ui/Screen/UserRegistration/PickHandleStep.svelte
  ui/index.js
  ui/index.js.map
  ui/lib/hash.js
  ui/lib/hotkeys.js
  ui/lib/orgMocks.js
  ui/lib/path.js
  ui/src/commitMocks.ts
  ui/src/config.ts
  ui/src/notification.ts
  ui/src/path.ts
  ui/src/source.ts
  ui/store/notification.js
Labels: improvement, ui

#334 feat(ui): visuals for add member to org flow
  cypress/integration/add_member_to_org.spec.js
  cypress/integration/org_registration.spec.js
  cypress/support/commands.js
  ui/App.svelte
  ui/DesignSystem/Component/Registration/NavigationButtons.svelte
  ui/DesignSystem/Component/Registration/StepModalLayout.svelte
  ui/DesignSystem/Component/Sidebar.svelte
  ui/DesignSystem/Component/index.js
  ui/Screen/Org.svelte
  ui/Screen/Org/MemberRegistration.svelte
  ui/Screen/Org/MembersMenu.svelte
  ui/Screen/Org/Projects.svelte
  ui/Screen/OrgRegistration.svelte
  ui/lib/hotkeys.js
  ui/src/avatar.ts
  ui/src/org.ts
  ui/src/path.ts
  ui/src/transaction.ts
Labels: feature, ui

#366 feat(ui): fix up input avatars for org & add-member-to-org registration flows
  cypress/integration/add_member_to_org.spec.js
  cypress/integration/org_registration.spec.js
  ui/DesignSystem/Primitive/Input/Text.svelte
  ui/Screen/Org/MemberRegistration.svelte
  ui/Screen/OrgRegistration.svelte
  ui/src/user.ts
Labels: improvement, ui

#351 fix: bundle missing library libhogweed
  package.json
Labels: bug, infrastructure

#368 refactor(ui): improve scalability of hotkeys
  cypress/integration/identity_creation.spec.js
  package.json
  ui/App.svelte
  ui/DesignSystem/Component/ModalLayout.svelte
  ui/Hotkeys.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Help.svelte
  ui/Screen/IdentityCreation.svelte
  ui/Screen/ProjectCreation.svelte
  ui/lib/hotkeys.js
  ui/src/theme.ts
Labels: improvement, ui

#360 feat(proxy): Return the member list for an Org
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/http/org.rs
  proxy/src/http/user.rs
  proxy/src/registry.rs
Labels: feature, proxy

#361 feat(ui): wire up org project list
  cypress/integration/add_member_to_org.spec.js
  proxy/src/http.rs
  proxy/src/http/org.rs
  proxy/src/registry.rs
  ui/DesignSystem/Component/AdditionalActionsDropdown.svelte
  ui/DesignSystem/Component/List.svelte
  ui/DesignSystem/Component/ProjectCard.svelte
  ui/DesignSystem/Component/Stat.svelte
  ui/DesignSystem/Component/Stats.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Avatar.svelte
  ui/DesignSystem/Primitive/Flex.svelte
  ui/DesignSystem/Primitive/Input/Checkbox.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Org.svelte
  ui/Screen/Org/Onboard.svelte
  ui/Screen/Org/Projects.svelte
  ui/Screen/Profile.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
  ui/src/org.ts
  ui/src/path.ts
  ui/src/project.ts
  yarn.lock
Labels: feature, ui

#379 feat: improve dev ergonomics
  DEVELOPMENT.md
  package.json
  proxy/src/http.rs
  rollup.app.js
Labels: improvement, infrastructure, proxy

#370 feat(proxy): persist transactions
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/error.rs
  proxy/src/http.rs
  proxy/src/http/avatar.rs
  proxy/src/http/control.rs
  proxy/src/http/error.rs
  proxy/src/http/identity.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/session.rs
  proxy/src/http/source.rs
  proxy/src/http/transaction.rs
  proxy/src/http/user.rs
  proxy/src/main.rs
  proxy/src/project.rs
  proxy/src/registry.rs
  proxy/src/registry/transaction.rs
  proxy/src/session.rs
  ui/src/transaction.ts
Labels: feature, proxy

#377 feat(ui): SegmentedControl component
  ui/DesignSystem/Component/SegmentedControl.svelte
  ui/DesignSystem/Component/index.js
  ui/Screen/DesignSystemGuide.svelte
Labels: feature, ui

#380 feat(proxy): improve session
  cypress/integration/identity_creation.spec.js
  proxy/src/avatar.rs
  proxy/src/http.rs
  proxy/src/http/control.rs
  proxy/src/http/identity.rs
  proxy/src/http/org.rs
  proxy/src/http/session.rs
  proxy/src/http/user.rs
  proxy/src/identity.rs
  proxy/src/registry.rs
  proxy/src/registry/transaction.rs
  proxy/src/session.rs
  ui/Screen/UserRegistration.svelte
Labels: feature, proxy

#381 chore(release): 0.0.10
  CHANGELOG.md
  package.json
Labels: infrastructure

#383 feat(proxy): extend session with settings
  proxy/src/http.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/session.rs
  proxy/src/session.rs
  ui/App.svelte
  ui/src/session.ts
  ui/src/settings.ts
Labels: feature, proxy

#389 feat(proxy): settings endpoints
  cypress/integration/org_registration.spec.js
  cypress/integration/user_registration.spec.js
  cypress/support/commands.js
  proxy/src/http.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/session.rs
  proxy/src/http/transaction.rs
  proxy/src/http/user.rs
  proxy/src/main.rs
  proxy/src/registry.rs
  proxy/src/registry/transaction.rs
  proxy/src/session.rs
  ui/App.svelte
  ui/src/api.ts
  ui/src/session.ts
  ui/src/transaction.ts
Labels: feature, proxy

#375 style(ui): settings
  ui/App.svelte
  ui/DesignSystem/Component/Sidebar.svelte
  ui/DesignSystem/Primitive/Button.svelte
  ui/DesignSystem/Primitive/Text.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Network.svelte
  ui/Screen/Profile.svelte
  ui/Screen/Profile/Settings.svelte
  ui/Screen/Profile/SettingsMenu.svelte
  ui/Screen/Settings.svelte
  ui/src/path.ts
Labels: feature, ui

#372 test(ui): add project registration specs
  cypress/integration/add_member_to_org.spec.js
  cypress/integration/org_member_addition.spec.js
  cypress/integration/org_registration.spec.js
  cypress/integration/project_registration.spec.js
  cypress/integration/project_source_browsing.spec.js
  cypress/support/commands.js
  ui/DesignSystem/Component/Dropdown.svelte
  ui/DesignSystem/Component/List.svelte
  ui/DesignSystem/Component/ProjectCard.svelte
  ui/DesignSystem/Component/Sidebar.svelte
  ui/DesignSystem/Component/Transaction.svelte
  ui/DesignSystem/Primitive/Flex.svelte
  ui/Screen/Org.svelte
  ui/Screen/Org/Onboard.svelte
  ui/Screen/Org/Projects.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Project.svelte
  ui/Screen/ProjectRegistration.svelte
  ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
Labels: improvement, ui

#390 feat(ui): wire up settings endpoints
  cypress/integration/identity_creation.spec.js
  cypress/integration/settings_specs.js
  cypress/support/commands.js
  proxy/src/session.rs
  public/colors.css
  tokens/colors.js
  ui/App.svelte
  ui/DesignSystem/Component/SegmentedControl.svelte
  ui/DesignSystem/Component/Transaction/Accordion.svelte
  ui/Hotkeys.svelte
  ui/Screen/Settings.svelte
  ui/Theme.svelte
  ui/src/api.ts
  ui/src/session.ts
  ui/src/settings.ts
  ui/src/theme.ts
  ui/src/transaction.ts
Labels: feature, ui

#393 feat: shareable entity identifiers
  proxy/src/http/control.rs
  proxy/src/http/identity.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/user.rs
  proxy/src/project.rs
  proxy/src/registry.rs
  ui/Screen/Org.svelte
  ui/Screen/Org/Projects.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/Source.svelte
  ui/src/org.ts
  ui/src/project.ts
Labels: feature, proxy, ui

#396 test(ui): improve identity creation specs
  cypress/integration/identity_creation.spec.js
  ui/DesignSystem/Primitive/Avatar.svelte
  ui/DesignSystem/Primitive/Icon/Badge.svelte
Labels: improvement, ui

#395 refactor(proxy): check applied transaction result
  cypress/integration/org_registration.spec.js
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/user.rs
  proxy/src/registry.rs
  proxy/src/registry/transaction.rs
Labels: improvement, proxy

#398 test(ui): re-enable existing user validation spec
  cypress/integration/user_registration.spec.js
Labels: improvement, ui

#399 fix(ui): show the correct avatars in summary pages
  ui/Screen/OrgRegistration.svelte
  ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
Labels: ui

#373 feat(ui): streamline transaction formatting
  cypress/integration/org_member_addition.spec.js
  cypress/integration/org_registration.spec.js
  cypress/integration/project_registration.spec.js
  cypress/integration/user_registration.spec.js
  ui/App.svelte
  ui/DesignSystem/Component/Transaction.svelte
  ui/DesignSystem/Component/Transaction/Accordion.svelte
  ui/DesignSystem/Primitive/Avatar.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Org/MemberRegistration.svelte
  ui/Screen/OrgRegistration.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Project.svelte
  ui/Screen/ProjectRegistration.svelte
  ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
  ui/Screen/TransactionDetails.svelte
  ui/Screen/UserRegistration/SubmitRegistrationStep.svelte
  ui/src/avatar.ts
  ui/src/org.ts
  ui/src/path.ts
  ui/src/project.ts
  ui/src/transaction.ts
  ui/src/user.ts
Labels: feature, ui

#403 style(ui): fix revision selector background
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
Labels: bug, ui

#402 feat(ui): org members list
  proxy/src/registry.rs
  ui/DesignSystem/Component/List.svelte
  ui/Screen/Org/Members.svelte
  ui/Screen/Org/Projects.svelte
  ui/Screen/Profile/Projects.svelte
  ui/src/org.ts
Labels: feature, ui

#374 style(ui): issues
  package.json
  ui/DesignSystem/Component/Comment.svelte
  ui/DesignSystem/Component/Label.svelte
  ui/DesignSystem/Component/ModalLayout.svelte
  ui/DesignSystem/Component/Timeline.svelte
  ui/DesignSystem/Component/Timeline/ActionItem.svelte
  ui/DesignSystem/Component/Timeline/CommentItem.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Icon/CloseIssue.svelte
  ui/DesignSystem/Primitive/Icon/Cross.svelte
  ui/DesignSystem/Primitive/Icon/CrossBig.svelte
  ui/DesignSystem/Primitive/Icon/Issue.svelte
  ui/DesignSystem/Primitive/Icon/Label.svelte
  ui/DesignSystem/Primitive/Icon/Replies.svelte
  ui/DesignSystem/Primitive/Icon/index.js
  ui/DesignSystem/Primitive/Input/Textarea.svelte
  ui/DesignSystem/Primitive/Input/index.js
  ui/DesignSystem/Primitive/Markdown.svelte
  ui/DesignSystem/Primitive/index.js
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/Issue.svelte
  ui/Screen/Project/Issues.svelte
  ui/Screen/Project/Issues/IssueCard.svelte
  ui/src/path.ts
  yarn.lock
Labels: feature, ui

#404 test(ui): add missing project creation specs
  cypress/integration/project_creation.spec.js
  proxy/src/http.rs
  ui/DesignSystem/Component/NotificationFaucet.svelte
  ui/DesignSystem/Primitive/Input/Directory.svelte
  ui/Screen/Project/Breadcrumb.svelte
  ui/Screen/ProjectCreation.svelte
Labels: improvement, ui

#408 style(ui): project page readme
  ui/DesignSystem/Component/SourceBrowser/Readme.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/Source.svelte
Labels: improvement, ui

#405 fix(proxy): only fetch commit for root tree
  proxy/src/coco.rs
  proxy/src/http/source.rs
Labels: bug, proxy

#410 fix(ui): check for project name length before registration
  ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
Labels: improvement, ui

#409 style(ui): support button styling
  ui/DesignSystem/Component/SupportButton.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Input/Text.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Project/SourceMenu.svelte
Labels: improvement, ui

#412 fix(ui): issues padding
  ui/Screen/Project/Issue.svelte
  ui/Screen/Project/Issues.svelte
Labels: improvement, ui

#407 feat: tx polling
  cypress/integration/org_member_addition.spec.js
  cypress/integration/org_registration.spec.js
  cypress/integration/routing.spec.js
  cypress/integration/user_registration.spec.js
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/http/control.rs
  proxy/src/http/identity.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/session.rs
  proxy/src/http/transaction.rs
  proxy/src/http/user.rs
  proxy/src/main.rs
  proxy/src/registry.rs
  proxy/src/registry/transaction.rs
  ui/App/TransactionCenter.svelte
  ui/DesignSystem/Component/ModalLayout.svelte
  ui/DesignSystem/Component/Remote.svelte
  ui/DesignSystem/Component/SidebarLayout.svelte
  ui/DesignSystem/Component/Transaction/Accordion.svelte
  ui/DesignSystem/Component/Transaction/Center.svelte
  ui/DesignSystem/Component/Transaction/Item.svelte
  ui/DesignSystem/Component/Transaction/ItemDescription.svelte
  ui/DesignSystem/Component/Transaction/List.svelte
  ui/DesignSystem/Component/Transaction/Statusbar.svelte
  ui/DesignSystem/Component/Transaction/Summary.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Flex.svelte
  ui/DesignSystem/Primitive/Icon/TransactionState.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/TransactionDetails.svelte
  ui/src/org.ts
  ui/src/remote.ts
  ui/src/session.ts
  ui/src/transaction.ts
Labels: feature, proxy, ui

#417 chore(release): 0.0.11
  CHANGELOG.md
  package.json
  proxy/Cargo.lock
  proxy/Cargo.toml
Labels: infrastructure

#425 fix: proxy lifecycle on macOS
  native/main.js
Labels: bug, infrastructure

#424 Remove joined date from member list
  ui/Screen/Org/Members.svelte
  ui/src/org.ts
Labels: improvement, ui

#429 refactor(ui): improve cypress spec reliability
  cypress/integration/project_creation.spec.js
  cypress/integration/project_source_browsing.spec.js
  cypress/support/commands.js
  package.json
  yarn.lock
Labels: improvement, ui

#430 fix: clippy CI
  .buildkite/run.sh
  proxy/src/registry/transaction.rs
Labels: improvement, infrastructure
