Repository radicle-dev/radicle-upstream, pull requests merged in 2020-11, with the labels that each got.

#1149 feat(proxy): Generate random cookie values
  proxy/Cargo.lock
  proxy/api/Cargo.toml
  proxy/api/src/context.rs
  proxy/api/src/error.rs
  proxy/api/src/http.rs
  proxy/api/src/http/identity.rs
  proxy/api/src/http/keystore.rs
  proxy/api/src/process.rs
Labels: improvement, proxy

#1158 refactor(tests): Enforce success responses from test helpers
  cypress/integration/routing.spec.js
  cypress/support/commands.js
Labels: improvement, infrastructure

#1161 chore(ui): run yarn to refresh yarn.lock
  .buildkite/run.sh
  yarn.lock
Labels: dependencies, ui

#1159 refactor(proxy): use thiserror for routing error messages
  proxy/api/src/http/error.rs
Labels: improvement, proxy

#1162 fix(ci): prevent concurrent builds on master branch
  .buildkite/pipeline.yaml
Labels: improvement, infrastructure

#1169 chore(proxy): update librad deps
  proxy/Cargo.lock
  proxy/api/src/http/control.rs
  proxy/coco/Cargo.toml
  proxy/coco/src/control.rs
  proxy/coco/src/lib.rs
  proxy/coco/src/project.rs
  proxy/coco/src/project/checkout.rs
  proxy/coco/src/project/create.rs
  proxy/coco/src/state.rs
  proxy/coco/src/state/error.rs
  proxy/coco/tests/common.rs
Labels: dependencies, improvement, proxy

#1160 chore(ci): Warn about focused tests
  .eslintrc.js
Labels: improvement, infrastructure, ui

#1171 style(ui): refactor FollowToggle component
  ui/DesignSystem/Component/FollowToggle.svelte
  ui/DesignSystem/Primitive/Button.svelte
  ui/Modal/ManagePeers/Peer.svelte
  ui/Modal/ManagePeers/PeerFollowRequest.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Profile/Following.svelte
  ui/Screen/Project.svelte
Labels: improvement, ui

#1164 style(ui): Improve loading screens + clean up Illustration component
  ui/App.svelte
  ui/DesignSystem/Component/EmptyState.svelte
  ui/DesignSystem/Component/Illustration.svelte
  ui/DesignSystem/Component/SourceBrowser/FileSource.svelte
  ui/Modal/ManagePeers.svelte
  ui/Modal/NewProject.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Profile/Following.svelte
  ui/Screen/Project/Issues.svelte
  ui/Screen/Project/Source.svelte
  ui/src/illustration.ts
  ui/src/session.ts
Labels: improvement, ui

#1167 chore: bump rust toolchain
  .buildkite/Dockerfile
  .buildkite/pipeline.yaml
  package.json
  proxy/api/src/context.rs
  proxy/api/src/http.rs
  proxy/api/src/lib.rs
  proxy/coco/src/lib.rs
  proxy/coco/src/peer/subroutines.rs
  proxy/coco/src/project/checkout.rs
  proxy/coco/src/project/peer.rs
  proxy/coco/src/request/existential.rs
  proxy/coco/src/request/states.rs
  proxy/coco/src/source.rs
  proxy/rust-toolchain
Labels: improvement, infrastructure, proxy

#1173 style(ui): clean up source page dropdowns
  ui/DesignSystem/Component/Header/Large.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/Screen/Project/Commit.svelte
  ui/Screen/Project/PeerSelector.svelte
Labels: improvement, ui

#1170 fix(proxy): persist temp dir on unseal in test mode
  cypress/integration/lock.spec.js
  cypress/integration/onboarding.spec.js
  proxy/Cargo.lock
  proxy/api/Cargo.toml
  proxy/api/src/process.rs
  proxy/api/src/service.rs
  ui/Screen/Lock.svelte
  ui/Screen/Onboarding.svelte
  ui/src/session.ts
Labels: improvement, proxy, ui

#1178 refactor(ui): improve lock screen tests
  cypress/integration/lock.spec.js
  ui/Screen/Lock.svelte
Labels: improvement, ui

#1185 fix(ci): don’t stall ci builds when tests fail
  package.json
Labels: bug, infrastructure

#1190 fix(proxy): extensive validation
  proxy/api/src/http/error.rs
  proxy/api/src/http/project.rs
  proxy/coco/src/keystore.rs
  proxy/coco/src/peer/run_state.rs
  proxy/coco/src/project/create.rs
  proxy/coco/src/project/create/validation.rs
  proxy/coco/src/state.rs
  proxy/coco/tests/common.rs
Labels: improvement, proxy

#1153 feat(proxy): Use password from user to unseal key store
  cypress/integration/lock.spec.js
  cypress/integration/onboarding.spec.js
  cypress/support/commands.js
  proxy/api/src/context.rs
  proxy/api/src/http/error.rs
  proxy/api/src/http/keystore.rs
  proxy/api/src/lib.rs
  proxy/api/src/process.rs
  proxy/api/src/service.rs
  proxy/coco/src/keystore.rs
  ui/Screen/Onboarding.svelte
  ui/src/session.ts
Labels: feature, proxy, security

#1193 refactor(ui): convert ipc to TypeScript
  .babelrc
  .gitignore
  DEVELOPMENT.md
  cypress/integration/project/checkout.spec.js
  cypress/integration/project/creation.spec.js
  cypress/integration/settings_specs.js
  native/ipc.ts
  native/main.js
  native/preload.d.ts
  package.json
  rollup.electron.js
  scripts/release.js
  tsconfig.json
  ui/DesignSystem/Component/Copyable.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/DesignSystem/Primitive/Input/Directory.svelte
  ui/Hotkeys.svelte
  ui/Modal/Shortcuts.svelte
  ui/Screen/Project.svelte
  ui/Screen/Settings.svelte
  yarn.lock
Labels: infrastructure, ui

#1180 chore(ui): show notifications for projects that can't be displayed
  native/main.js
  proxy/api/src/http/project.rs
  ui/Screen/Profile/Projects.svelte
  ui/src/error.ts
  ui/src/profile.ts
  ui/src/project.ts
Labels: improvement, ui

#1194 feat(ui): lock screen on key store unseal
  ui/App.svelte
  ui/Screen/Lock.svelte
  ui/Screen/Onboarding.svelte
  ui/Screen/Onboarding/EnterPassphrase.svelte
  ui/src/session.ts
Labels: improvement, ui

#1195 chore(ui): remove "clear session" button from settings
  QA.md
  cypress/integration/settings_specs.js
  proxy/api/src/http/session.rs
  proxy/api/src/session.rs
  ui/Screen/Settings.svelte
  ui/src/session.ts
Labels: ui

#1196 chore(ui): convert `native/main` to TypeScript
  native/main.ts
  package.json
  rollup.electron.js
  yarn.lock
Labels: improvement, ui

#1200 fix(proxy): always overwrite git helper with latest one
  proxy/coco/src/git_helper.rs
Labels: improvement, infrastructure

#1203 chore(ui): convert remaining UI js files
  ui/DesignSystem/Component/Header/index.ts
  ui/DesignSystem/Component/index.ts
  ui/DesignSystem/Primitive/Input/index.ts
  ui/DesignSystem/Primitive/index.ts
Labels: improvement, ui

#1204 chore(ui): enable "noEmit" in tsconfig.json
  .gitignore
  tsconfig.json
Labels: improvement, ui

#1177 fix(proxy): change announcement strategy
  proxy/Cargo.lock
  proxy/coco/Cargo.toml
  proxy/coco/src/peer/announcement.rs
  proxy/coco/src/peer/gossip.rs
  proxy/coco/src/peer/run_state.rs
  proxy/coco/src/state.rs
Labels: bug, proxy

#1202 refactor(ui): consolidate Electron IPC stub in tests
  .buildkite/run.sh
  cypress/integration/project/checkout.spec.js
  cypress/integration/project/creation.spec.js
  cypress/integration/settings_specs.js
  cypress/support/index.js
  cypress/support/ipc-stub.ts
  cypress/tsconfig.json
  package.json
  yarn.lock
Labels: infrastructure, ui

#1207 chore(build): cleanup all rollup artifacts before build
  package.json
Labels: improvement, infrastructure

#1183 refactor(proxy): move auth token logic into context
  proxy/api/src/context.rs
  proxy/api/src/http.rs
  proxy/api/src/http/keystore.rs
Labels: improvement, proxy

#1211 refactor(ui): convert cypress tests to TypeScript
  cypress/integration/lock.spec.ts
  cypress/integration/onboarding.spec.js
  cypress/integration/onboarding.spec.ts
  cypress/integration/project/checkout.spec.ts
  cypress/integration/project/creation.spec.js
  cypress/integration/project/creation.spec.ts
  cypress/integration/project/peer_management.spec.ts
  cypress/integration/project/source_browsing.spec.ts
  cypress/integration/routing.spec.ts
  cypress/integration/settings.spec.ts
  cypress/integration/user_profile.spec.js
  cypress/integration/user_profile.spec.ts
  cypress/support/commands.js
  cypress/support/commands.ts
  cypress/support/index.ts
Labels: improvement, infrastructure

#1212 feature(proxy): use port with less bind conflicts
  DEVELOPMENT.md
  cypress/support/commands.ts
  package.json
  proxy/README.md
  proxy/api/src/process.rs
  ui/src/api.ts
  ui/src/localPeer.ts
Labels: feature, proxy

#1213 chore(ci): run master build on preview agent
  .buildkite/pipeline.yaml
Labels: improvement, infrastructure

#1209 feature(ui): show error when proxy process exits
  cypress/integration/routing.spec.ts
  cypress/support/ipc-stub.ts
  cypress/tsconfig.json
  native/ipc-types.ts
  native/main.ts
  native/preload.d.ts
  native/preload.js
  ui/App.svelte
  ui/DesignSystem/Component/Copyable.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/DesignSystem/Primitive/Input/Directory.svelte
  ui/Hotkeys.svelte
  ui/Modal/Shortcuts.svelte
  ui/Screen/Bsod.svelte
  ui/Screen/Project.svelte
  ui/Screen/Settings.svelte
  ui/src/error.ts
  ui/src/ipc.ts
  ui/src/session.ts
Labels: feature, improvement, ui

#1217 fix(proxy): do not drop event tasks
  proxy/api/src/process.rs
  proxy/coco/src/spawn_abortable.rs
Labels: bug, proxy

#1220 chore: pre-commit hook fails on lint warnings
  package.json
Labels: improvement, ui

#1205 fix(proxy): add include to project creation
  proxy/Cargo.lock
  proxy/coco/Cargo.toml
  proxy/coco/src/peer.rs
  proxy/coco/src/peer/include.rs
  proxy/coco/src/peer/run_state.rs
  proxy/coco/src/peer/subroutines.rs
  proxy/coco/src/peer/sync.rs
  proxy/coco/src/project/create/validation.rs
  proxy/coco/src/source.rs
  proxy/coco/src/state.rs
Labels: improvement, proxy

#1222 fix(proxy): only set upstream branch on new project
  proxy/coco/src/project/create/validation.rs
Labels: improvement, proxy

#1215 chore(ui): update svelte toolchain
  package.json
  rollup.app.js
  ui/DesignSystem/Component/HorizontalMenu.svelte
  ui/DesignSystem/Component/HorizontalMenu/MenuItem.svelte
  ui/DesignSystem/Component/Remote.svelte
  ui/src/__mocks__/api.ts
  ui/src/localPeer.ts
  ui/src/notification.ts
  ui/src/project.ts
  ui/src/remote.ts
  ui/src/search.ts
  ui/src/session.ts
  ui/src/source.ts
  ui/src/validation.ts
  yarn.lock
Labels: dependencies, ui

#1216 feat(ui): show proxy logs when proxy crashes
  QA.md
  cypress/integration/routing.spec.ts
  cypress/support/ipc-stub.ts
  ui/Screen/Bsod.svelte
  ui/src/error.ts
  ui/src/ipc.ts
  ui/src/session.ts
Labels: improvement, ui

#1228 feat(ui): reduce number of retries after proxy restart
  ui/Screen/Onboarding.svelte
  ui/src/api.ts
  ui/src/session.ts
Labels: improvement, ui

#1237 fix(ui): remove project name from manage remote modal
  cypress/integration/project/peer_management.spec.ts
  ui/Modal/ManagePeers.svelte
  ui/Modal/ManagePeers/Peer.svelte
  ui/Modal/ManagePeers/PeerFollowRequest.svelte
Labels: improvement, ui

#1246 chore(ui): bump twemoji dependency
  package.json
  yarn.lock
Labels: dependencies, ui

#1221 feat(ui): introduce structured error logging
  ui/App.svelte
  ui/DesignSystem/Component/Remote.svelte
  ui/Screen/Onboarding.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/UserProfile/Projects.svelte
  ui/src/error.ts
  ui/src/profile.ts
  ui/src/session.ts
Labels: improvement, ui

#1250 feat(ui): log unhandled exceptions
  ui/src/error.ts
Labels: feature, ui

#1253 chore(ui): update ui deps
  package.json
  ui/DesignSystem/Component/RemoteHelperHint.svelte
  ui/Screen/Onboarding/EnterPassphrase.svelte
  ui/Screen/Onboarding/Success.svelte
  ui/Screen/Project/Commit.svelte
  ui/Screen/Project/Issue.svelte
  ui/Screen/Project/Issues/IssueCard.svelte
  ui/Screen/Project/Untracked.svelte
  ui/Screen/Settings.svelte
  yarn.lock
Labels: dependencies, ui

#1256 fix(ui): only allow scripts from origin
  public/index.html
Labels: security, ui

#1238 refactor(proxy): improve project search semantics
  proxy/Cargo.lock
  proxy/coco/src/peer/control.rs
  proxy/coco/src/peer/run_state.rs
  proxy/coco/src/request/states.rs
  proxy/coco/src/request/waiting_room.rs
Labels: improvement, proxy

#1257 fix(ui): remove unused props
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Settings.svelte
Labels: ui

#1261 fix(ui): move `go to profile` to isExperimental
  ui/Screen/Project/PeerSelector.svelte
Labels: ui

#1260 style(ui): add 💻 icon to peerId
  ui/DesignSystem/Component/Header/Large.svelte
  ui/DesignSystem/Component/PeerId.svelte
  ui/DesignSystem/Component/index.ts
  ui/DesignSystem/Primitive/Icon/Computer.svelte
  ui/DesignSystem/Primitive/Icon/index.ts
  ui/Screen/Onboarding/Success.svelte
  ui/Screen/Settings.svelte
Labels: design, improvement, ui

#1247 feat(proxy): persist WaitingRoom
  proxy/api/src/process.rs
  proxy/coco/src/lib.rs
  proxy/coco/src/peer.rs
  proxy/coco/src/peer/run_state.rs
  proxy/coco/src/peer/run_state/command.rs
  proxy/coco/src/peer/run_state/config.rs
  proxy/coco/src/peer/run_state/input.rs
  proxy/coco/src/peer/subroutines.rs
  proxy/coco/src/peer/waiting_room.rs
  proxy/coco/tests/gossip.rs
  proxy/coco/tests/replication.rs
Labels: improvement, proxy

#1267 fix(ui): truncate notification messages to fit into view
  ui/DesignSystem/Component/Notification.svelte
  ui/DesignSystem/Component/NotificationFaucet.svelte
Labels: bug, ui

#1277 fix(proxy): surf branches
  proxy/Cargo.lock
  proxy/coco/Cargo.toml
Labels: dependencies, improvement, proxy

#1265 fix(ui): improve error code for backend termination
  ui/src/error.ts
Labels: improvement, ui

#1264 chore(ui): add basic tests for project following
  cypress/integration/project/follow.spec.ts
  cypress/support/commands.ts
  ui/Modal/Search.svelte
  ui/Screen/Profile/Following.svelte
Labels: improvement, ui

#1280 fix(ui): specify List keys
  ui/DesignSystem/Component/List.svelte
  ui/Screen/Profile/Following.svelte
Labels: ui

#1278 feat(proxy): push all branches when creating a project
  proxy/api/src/http/project.rs
  proxy/coco/src/project/create/validation.rs
Labels: improvement, proxy

#1293 refactor(ui): remove expand icon from dropdown items
  ui/Screen/Project/PeerSelector.svelte
Labels: improvement, ui

#1284 chore(ui): update external radicle links
  native/main.ts
  ui/DesignSystem/Component/RemoteHelperHint.svelte
  ui/Screen/Settings.svelte
Labels: documentation, ui

#1291 fix(ui): don't show stats that equal zero
  ui/DesignSystem/Component/Header/Large.svelte
  ui/DesignSystem/Component/Stats.svelte
Labels: improvement, ui

#1300 chore(proxy): bump surf dep
  proxy/Cargo.lock
  proxy/coco/Cargo.toml
Labels: bug, dependencies, proxy

#1303 build: rename binary to "Radicle Upstream"
  package.json
Labels: improvement, infrastructure

#1304 fix(proxy): return tracking remotes as contributor
  proxy/coco/src/state.rs
Labels: bug, proxy

#1305 fix(proxy): fix announcemnets
  proxy/coco/src/peer/announcement.rs
Labels: bug, proxy

#1288 refactor(proxy): simplify `CreateRequest` control input
  proxy/coco/src/peer/run_state.rs
  proxy/coco/src/peer/run_state/input.rs
  proxy/coco/src/peer/subroutines.rs
Labels: improvement, proxy

#1290 refactor(ui): change checkout button copy
  ui/Screen/Project.svelte
  ui/Screen/Project/Source.svelte
  ui/Screen/Project/Source/CheckoutButton.svelte
  ui/src/project.ts
Labels: improvement, ui

#1287 chore(ui): update ui deps
  package.json
  ui/src/screen/project.ts
  yarn.lock
Labels: dependencies, ui

#1301 style(ui): align peerId and radicleId styling in the app
  ui/DesignSystem/Component/Header/Large.svelte
  ui/DesignSystem/Component/PeerId.svelte
  ui/DesignSystem/Component/RadicleId.svelte
  ui/DesignSystem/Component/ShareableIdentifier.svelte
  ui/DesignSystem/Component/StyledCopyable.svelte
  ui/DesignSystem/Component/index.ts
  ui/Modal/ManagePeers/Peer.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Discovery/Project.svelte
  ui/Screen/Profile/Following.svelte
Labels: design, improvement, ui

#1316 chore(proxy): stream seeds when disconnected
  proxy/api/src/process.rs
Labels: improvement, proxy

#1318 chore(ui): fix setting bottom padding
  ui/Screen/Settings.svelte
Labels: improvement, ui

#1320 chore: git-ignore ./sandbox
  .gitignore
Labels: improvement, infrastructure

#1313 chore(ui): update copy
  ui/Modal/ManagePeers.svelte
  ui/Modal/NewProject.svelte
  ui/Modal/Search.svelte
  ui/Screen/Lock.svelte
  ui/Screen/Onboarding/EnterPassphrase.svelte
  ui/Screen/Onboarding/Success.svelte
  ui/Screen/Settings.svelte
Labels: improvement, ui

#1325 chore: update reset script
  scripts/reset-state.sh
Labels: improvement, infrastructure

#1323 fix(ui): remove paste shortcut
  ui/Modal/ManagePeers.svelte
  ui/Modal/Search.svelte
  ui/Screen/Settings.svelte
Labels: improvement, ui

#1329 chore(proxy): bump deps
  proxy/Cargo.lock
  proxy/coco/Cargo.toml
Labels: dependencies, proxy

#1349 fix(ui): fix external support links
  ui/Screen/Bsod.svelte
  ui/Screen/Settings.svelte
Labels: improvement, ui

#1354 chore(proxy): filter log lines from `quinn` create
  proxy/api/src/main.rs
Labels: improvement, proxy

#1357 fix(ui): remove logging on opening external links
  native/main.ts
Labels: ui

#1353 fix(ui) fix BSOD overflow scroll bug
  ui/Screen/Bsod.svelte
Labels: improvement, ui

#1332 fix(proxy): query peer refs after tracking
  proxy/Cargo.lock
  proxy/coco/src/peer/gossip.rs
  proxy/coco/src/peer/subroutines.rs
  proxy/coco/src/state.rs
  proxy/coco/tests/replication.rs
Labels: improvement, proxy

#1330 refactor(proxy): Avoid confusing errors in http route matching
  proxy/api/src/http/control.rs
  proxy/api/src/http/identity.rs
  proxy/api/src/http/project.rs
  proxy/api/src/http/project/request.rs
  proxy/api/src/http/session.rs
  proxy/api/src/http/source.rs
Labels: improvement, proxy

#1355 fix(docs): document that AppImage needs to be made executable
  QA.md
Labels: documentation, improvement

#1370 fix(ui): align checkout modal with button
  ui/Screen/Project/Source/CheckoutButton.svelte
Labels: improvement, ui

#1374 fix(proxy): update to radicle-surf v0.5.3
  proxy/Cargo.lock
Labels: dependencies, improvement, proxy

#1385 fix(proxy): validate default git config
  proxy/api/src/http/error.rs
  proxy/coco/src/project/create/validation.rs
Labels: improvement, proxy

#1382 fix(ui): make stats component reactive
  ui/DesignSystem/Component/Stats.svelte
  ui/src/localPeer.ts
Labels: bug, ui

#1388 chore: add links update to `DEVELOPMENT.md`
  DEVELOPMENT.md
Labels: documentation, improvement

#1387 fix(ui): Increase hit area for sidebar buttons
  ui/DesignSystem/Component/ConnectionStatusIndicator.svelte
  ui/DesignSystem/Component/Sidebar.svelte
Labels: design, improvement, ui

#1386 fix(ui): trim whitespace from search input
  cypress/integration/project/follow.spec.ts
  ui/Modal/Search.svelte
Labels: ui

#1381 fix(ui): Update doc link
  ui/DesignSystem/Component/RemoteHelperHint.svelte
  ui/Screen/Onboarding/Success.svelte
Labels: documentation, improvement, ui

#1379 fix(ci): timeout for proxy tests
  .buildkite/run.sh
Labels: improvement, infrastructure

#1377 fix(proxy): only save most recent logs from proxy
  cypress/integration/routing.spec.ts
  jest.config.js
  native/ipc-types.ts
  native/main.ts
  native/proxy-process-manager.test.ts
  native/proxy-process-manager.ts
  package.json
  ui/Screen/Bsod.svelte
  yarn.lock
Labels: improvement, ui

#1392 fix(proxy): remove seeds guard to enable reconnect
  proxy/coco/src/config.rs
Labels: improvement, proxy

#1395 style(ui): update icons
  public/favicon.png
  public/icon.icns
  public/icon.png
  public/icon@2x.png
Labels: improvement, ui

#1372 fix(ui) prevent images in markdown from overflowing
  ui/DesignSystem/Primitive/Markdown.svelte
Labels: improvement, ui

#1400 fix(proxy): avoid double seed emission
  proxy/api/src/process.rs
Labels: bug, proxy

#1371 fix(proxy): remote tracking semantics
  package.json
  proxy/api/src/http/identity.rs
  proxy/api/src/http/project.rs
  proxy/coco/src/state.rs
  ui/DesignSystem/Component/Badge.svelte
  ui/DesignSystem/Component/PeerId.svelte
  ui/DesignSystem/Component/PeerSelector.svelte
  ui/DesignSystem/Component/PeerSelector/Entry.svelte
  ui/DesignSystem/Component/PeerSelector/Peer.svelte
  ui/DesignSystem/Primitive/Emoji.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/PeerSelector.svelte
  ui/src/screen/project.ts
Labels: bug, improvement, proxy

#1398 fix(proxy): quit app when render process crashes
  native/main.ts
Labels: improvement, ui

#1393 feat: reactive remote management
  proxy/api/src/notification.rs
  proxy/coco/src/peer/run_state.rs
  proxy/coco/src/peer/run_state/input.rs
  proxy/coco/tests/gossip.rs
  proxy/coco/tests/replication.rs
  ui/DesignSystem/Component/SidebarLayout.svelte
  ui/Screen/Project.svelte
  ui/src/localPeer.ts
  ui/src/project.ts
  ui/src/screen/project.ts
Labels: feature, proxy, ui

#1406 build: automate macOS package notarization
  DEVELOPMENT.md
  builder/entitlements.mac.plist
  builder/notarize.js
  package.json
  scripts/reset-state.sh
  yarn.lock
Labels: infrastructure

#1405 chore(proxy): add support for more syntaxes
  QA.md
  package.json
  proxy/assets/Solidity.sublime-syntax
  proxy/assets/Svelte.sublime-syntax
  proxy/assets/TOML.sublime-syntax
  proxy/assets/TypeScript.sublime-syntax
  proxy/assets/TypeScriptReact.sublime-syntax
  proxy/coco/src/source.rs
Labels: dependencies, improvement, proxy

#1411 build: instructions how to upload releases
  DEVELOPMENT.md
Labels: documentation, feature

#1422 chore(ui): correct support link on BSOD
  ui/Screen/Bsod.svelte
Labels: improvement, ui

#1431 chore(ui): correct colors with spec
  cypress/integration/settings.spec.ts
  proxy/api/src/session/settings.rs
  public/colors.css
  ui/Theme.svelte
  ui/src/__mocks__/api.ts
  ui/src/settings.ts
Labels: improvement, ui

#1423 chore(ci): don’t build snap images since they are broken
  .buildkite/pipeline.yaml
  DEVELOPMENT.md
  package.json
Labels: improvement, infrastructure
