Repository radicle-dev/radicle-upstream, pull requests merged in 2020-08, with the labels that each got.

#712 feat(ui): send funds flow
  cypress/integration/org_wallet.spec.js
  cypress/integration/send_funds.spec.js
  cypress/integration/user_wallet.spec.js
  proxy/src/http/control.rs
  proxy/src/http/org.rs
  proxy/src/http/user.rs
  proxy/src/registry.rs
  proxy/src/registry/transaction.rs
  ui/App.svelte
  ui/DesignSystem/Component/Rad.svelte
  ui/DesignSystem/Component/Transaction.svelte
  ui/DesignSystem/Component/Transaction/Header.svelte
  ui/DesignSystem/Component/Transaction/Item.svelte
  ui/DesignSystem/Component/Wallet.svelte
  ui/DesignSystem/Component/Wallet/SendReceive.svelte
  ui/DesignSystem/Component/Wallet/TxList.svelte
  ui/DesignSystem/Component/Wallet/TxListItem.svelte
  ui/DesignSystem/Primitive/Icon/ArrowRight.svelte
  ui/DesignSystem/Primitive/Icon/index.js
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Org/Fund.svelte
  ui/Screen/Org/MemberRegistration.svelte
  ui/Screen/OrgRegistration.svelte
  ui/Screen/Profile/Wallet.svelte
  ui/Screen/Project/Source.svelte
  ui/Screen/ProjectRegistration.svelte
  ui/Screen/SendFunds.svelte
  ui/Screen/TransactionDetails.svelte
  ui/Screen/UserRegistration/SubmitRegistrationStep.svelte
  ui/src/account.ts
  ui/src/currency.ts
  ui/src/identity.ts
  ui/src/org.ts
  ui/src/path.ts
  ui/src/transaction.ts
  ui/src/transfer.ts
Labels: feature, ui

#747 chore(ui): bug fixing
  cypress/integration/project_source_browsing.spec.js
  ui/DesignSystem/Component/AdditionalActionsDropdown.svelte
  ui/DesignSystem/Component/SourceBrowser/FileSource.svelte
  ui/DesignSystem/Primitive/Icon/Spinner.svelte
  ui/DesignSystem/Primitive/Input/Textarea.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Settings.svelte
Labels: improvement, ui

#731 style(ui): Reformat and standardize all RadUrns
  ui/DesignSystem/Component/AdditionalActionsDropdown.svelte
  ui/DesignSystem/Component/Copyable.svelte
  ui/DesignSystem/Component/Header/Large.svelte
  ui/DesignSystem/Component/Transaction.svelte
  ui/DesignSystem/Component/Urn.svelte
  ui/DesignSystem/Component/Wallet.svelte
  ui/DesignSystem/Component/Wallet/Receive.svelte
  ui/DesignSystem/Primitive/Icon/Ellipses.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Discovery/Project.svelte
  ui/Screen/Project/Source.svelte
Labels: improvement, ui

#750 fix(ci): add timezone to test:integration command
  package.json
Labels: infrastructure

#752 chore(proxy): bump librad
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/coco/config.rs
  proxy/src/coco/peer.rs
Labels: dependencies, proxy

#755 fix(ui): clean up
  public/typography.css
  ui/DesignSystem/Component/Notification.svelte
  ui/DesignSystem/Component/ProjectCard.svelte
  ui/DesignSystem/Component/Urn.svelte
Labels: bug, ui

#758 feat(ui): add notification when copying urn
  ui/DesignSystem/Component/Copyable.svelte
  ui/DesignSystem/Component/Header/Large.svelte
  ui/DesignSystem/Component/Transaction.svelte
  ui/DesignSystem/Component/Urn.svelte
  ui/DesignSystem/Component/Wallet/Receive.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Discovery/Project.svelte
  ui/Screen/Project/Source.svelte
Labels: improvement, ui

#759 feat(ui): add keyboard shortcuts
  ui/App.svelte
  ui/DesignSystem/Primitive/Button.svelte
  ui/Hotkeys.svelte
  ui/Screen/Help.svelte
  ui/Screen/Settings.svelte
  ui/Screen/Shortcuts.svelte
  ui/src/path.ts
  ui/src/settings.ts
Labels: improvement, ui

#764 chore(proxy): bump librad
  proxy/Cargo.lock
  proxy/Cargo.toml
Labels: dependencies, improvement

#722 feat: project checkout
  .gitignore
  cypress/integration/project_checkout.spec.js
  cypress/integration/project_creation.spec.js
  native/ipc.js
  native/main.js
  package.json
  proxy/src/coco.rs
  proxy/src/coco/peer.rs
  proxy/src/coco/source.rs
  proxy/src/error.rs
  proxy/src/http/control.rs
  proxy/src/http/project.rs
  proxy/src/http/source.rs
  proxy/src/lib.rs
  proxy/src/main.rs
  proxy/src/project.rs
  proxy/tests/checkout.rs
  ui/DesignSystem/Component/AdditionalActionsDropdown.svelte
  ui/DesignSystem/Component/Notification.svelte
  ui/DesignSystem/Component/NotificationFaucet.svelte
  ui/DesignSystem/Component/Tooltip.svelte
  ui/DesignSystem/Component/Urn.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Project/CheckoutButton.svelte
  ui/Screen/Project/Source.svelte
  ui/src/config.ts
  ui/src/notification.ts
  ui/src/project.ts
Labels: feature, proxy, ui

#765 fix(ui): update source browsing
  README.md
  ui/DesignSystem/Component/SourceBrowser/FileSource.svelte
  ui/DesignSystem/Component/SourceBrowser/Readme.svelte
  ui/DesignSystem/Primitive/Markdown.svelte
  ui/src/source.ts
Labels: improvement, ui

#757 feat(proxy): tracked identities endpoint
  proxy/src/http/identity.rs
  proxy/src/identity.rs
Labels: feature, proxy

#727 fix(proxy): project init
  cypress/integration/project_creation.spec.js
  proxy/src/coco.rs
  proxy/src/coco/control.rs
  proxy/src/coco/peer.rs
  proxy/src/coco/project.rs
  proxy/src/error.rs
  proxy/src/http/project.rs
  ui/DesignSystem/Primitive/Input/Text.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/ProjectCreation.svelte
  ui/src/project.test.ts
  ui/src/project.ts
Labels: improvement, proxy

#773 chore(proxy): remove needless_pass_by_value check
  proxy/src/coco/control.rs
  proxy/src/coco/peer.rs
  proxy/src/coco/source.rs
  proxy/src/http/control.rs
  proxy/src/http/identity.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/source.rs
  proxy/src/http/user.rs
  proxy/src/identity.rs
  proxy/src/main.rs
  proxy/tests/checkout.rs
Labels: easy, proxy

#772 style(ui): update project page layout
  cypress/integration/project_source_browsing.spec.js
  public/global.css
  ui/App.svelte
  ui/DesignSystem/Component/NotificationFaucet.svelte
  ui/DesignSystem/Component/SidebarLayout.svelte
  ui/DesignSystem/Component/SourceBrowser/File.svelte
  ui/DesignSystem/Component/SourceBrowser/Folder.svelte
  ui/DesignSystem/Primitive/Icon/Chevron.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/Commits.svelte
  ui/Screen/Project/Source.svelte
Labels: improvement, ui

#778 fix(style): typography tweaks
  public/typography.css
  ui/Screen/DesignSystemGuide.svelte
Labels: improvement, ui

#782 chore(proxy): tests and binaries can be run with lint warnings
  .buildkite/run.sh
  proxy/src/lib.rs
Labels: improvement, infrastructure

#783 doc: update test preparation in developer manual
  .buildkite/run.sh
  DEVELOPMENT.md
Labels: improvement, infrastructure

#784 chore(proxy): bump librad and keystore
  proxy/Cargo.lock
  proxy/Cargo.toml
Labels: dependencies, improvement

#769 feat: set up remote helper
  cypress/integration/project_checkout.spec.js
  proxy/src/coco.rs
  proxy/src/coco/git_helper.rs
  proxy/src/config.rs
  proxy/src/http/session.rs
  proxy/src/main.rs
  proxy/src/project.rs
  proxy/src/session.rs
  ui/DesignSystem/Component/Copyable.svelte
  ui/DesignSystem/Component/RemoteHelperHint.svelte
  ui/DesignSystem/Component/Urn.svelte
  ui/DesignSystem/Component/index.js
  ui/Screen/Profile/ProjectsMenu.svelte
  ui/Screen/Project/CheckoutButton.svelte
  ui/Screen/ProjectCreation.svelte
  ui/src/session.ts
Labels: dependencies, feature

#787 fix(ui): fix remote helper export
  ui/DesignSystem/Component/RemoteHelperHint.svelte
  ui/Screen/Project/CheckoutButton.svelte
Labels: bug, ui

#793 fix(ui): Accessible hotkeys for other layouts
  ui/Hotkeys.svelte
  ui/Screen/Shortcuts.svelte
Labels: improvement, ui

#789 feat(proxy): filter projects by user URN
  proxy/src/http/project.rs
  proxy/src/project.rs
Labels: feature, proxy

#795 feat(ui): go to user profile aka visitor view
  ui/App.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/DesignSystem/Primitive/Icon/Open.svelte
  ui/DesignSystem/Primitive/Icon/index.js
  ui/Screen/UserProfile.svelte
  ui/src/path.ts
Labels: feature, ui

#800 chore(proxy): seed improvements
  proxy/src/coco.rs
  proxy/src/coco/config.rs
  proxy/src/coco/seed.rs
  proxy/src/lib.rs
  proxy/src/main.rs
Labels: improvement, proxy

#813 fix(ui): improve error messaging in project creation
  cypress/integration/project_creation.spec.js
  ui/Screen/ProjectCreation.svelte
Labels: improvement, ui

#817 refactor: remove registry
  cypress/integration/identity_creation.spec.js
  cypress/integration/org_member_addition.spec.js
  cypress/integration/org_registration.spec.js
  cypress/integration/org_wallet.spec.js
  cypress/integration/project_creation.spec.js
  cypress/integration/project_registration.spec.js
  cypress/integration/routing.spec.js
  cypress/integration/send_funds.spec.js
  cypress/integration/settings_specs.js
  cypress/integration/user_registration.spec.js
  cypress/integration/user_wallet.spec.js
  cypress/support/commands.js
  proxy/Cargo.lock
  proxy/api/Cargo.toml
  proxy/api/src/avatar.rs
  proxy/api/src/error.rs
  proxy/api/src/http.rs
  proxy/api/src/http/account.rs
  proxy/api/src/http/avatar.rs
  proxy/api/src/http/control.rs
  proxy/api/src/http/id.rs
  proxy/api/src/http/identity.rs
  proxy/api/src/http/notification.rs
  proxy/api/src/http/org.rs
  proxy/api/src/http/project.rs
  proxy/api/src/http/session.rs
  proxy/api/src/http/source.rs
  proxy/api/src/http/transaction.rs
  proxy/api/src/http/user.rs
  proxy/api/src/identity.rs
  proxy/api/src/keystore.rs
  proxy/api/src/lib.rs
  proxy/api/src/main.rs
  proxy/api/src/notification.rs
  proxy/api/src/project.rs
  proxy/api/src/registry.rs
  proxy/api/src/registry/transaction.rs
  proxy/api/src/session.rs
  proxy/coco/src/config.rs
  proxy/coco/src/control.rs
  proxy/coco/src/error.rs
  proxy/coco/src/peer.rs
  proxy/coco/src/source.rs
  ui/DesignSystem/Component/Header/Large.svelte
  ui/DesignSystem/Component/SidebarLayout.svelte
  ui/Screen/Profile.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Profile/Wallet.svelte
  ui/Screen/Project.svelte
  ui/Screen/Settings.svelte
  ui/src/__mocks__/api.ts
  ui/src/session.test.ts
  ui/src/session.ts
  ui/src/settings.ts
  ui/src/transaction.ts
Labels: dependencies, improvement, proxy, ui

#818 feat: maintainer badge
  proxy/api/src/http/project.rs
  proxy/api/src/project.rs
  ui/DesignSystem/Component/Badge.svelte
  ui/DesignSystem/Component/ProjectCard.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/DesignSystem/Component/index.js
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Project/Source.svelte
  ui/src/__mocks__/api.ts
  ui/src/badge.ts
  ui/src/project.ts
Labels: feature

#825 fix(proxy): project creation from repo without master
  proxy/coco/src/source.rs
  ui/Screen/ProjectCreation.svelte
Labels: bug, proxy

#816 feat(ui): visitor profile view
  cypress/integration/user_profile.spec.js
  proxy/api/src/http/identity.rs
  ui/App.svelte
  ui/DesignSystem/Component/ProjectList.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/DesignSystem/Component/index.js
  ui/Screen/Profile/Projects.svelte
  ui/Screen/UserProfile.svelte
  ui/Screen/UserProfile/Projects.svelte
  ui/src/identity.ts
  ui/src/path.ts
  ui/src/project.ts
Labels: feature, ui

#829 fix(ci): proxy binary naming
  package.json
Labels: bug, infrastructure

#824 chore(proxy): remove default seed
  proxy/api/src/http/session.rs
  proxy/api/src/session.rs
Labels: improvement, proxy

#830 chore(proxy): newtype for Oid
  proxy/api/src/http/source.rs
  proxy/coco/src/lib.rs
  proxy/coco/src/oid.rs
  proxy/coco/src/source.rs
Labels: improvement, proxy

#776 feat(ui): tracking tab
  ui/DesignSystem/Component/AdditionalActionsDropdown.svelte
  ui/DesignSystem/Component/Header/Large.svelte
  ui/DesignSystem/Component/Hoverable.svelte
  ui/DesignSystem/Component/List.svelte
  ui/DesignSystem/Component/ProjectList.svelte
  ui/DesignSystem/Component/TrackToggle.svelte
  ui/DesignSystem/Component/Transaction.svelte
  ui/DesignSystem/Component/Urn.svelte
  ui/DesignSystem/Component/Wallet/Receive.svelte
  ui/DesignSystem/Component/index.js
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Discovery/Project.svelte
  ui/Screen/Profile.svelte
  ui/Screen/Profile/Tracking.svelte
  ui/Screen/Project/Source.svelte
  ui/src/config.ts
  ui/src/org.test.ts
  ui/src/org.ts
  ui/src/path.ts
Labels: feature, ui

#738 feat(ui): navigate-to-project modal
  ui/App.svelte
  ui/DesignSystem/Component/ModalOverlay.svelte
  ui/DesignSystem/Component/SearchModal.svelte
  ui/DesignSystem/Component/Sidebar.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Avatar.svelte
  ui/DesignSystem/Primitive/Emoji.svelte
  ui/DesignSystem/Primitive/Input/Text.svelte
  ui/DesignSystem/Primitive/index.js
  ui/Hotkeys.svelte
  ui/Screen/Discovery/Project.svelte
  ui/Screen/Project/Untracked.svelte
  ui/Screen/Search.svelte
  ui/src/modal.ts
  ui/src/path.ts
  ui/src/search.ts
Labels: ui

#843 refactor(proxy): extract context
  proxy/api/src/context.rs
  proxy/api/src/http.rs
  proxy/api/src/http/control.rs
  proxy/api/src/http/identity.rs
  proxy/api/src/http/project.rs
  proxy/api/src/http/session.rs
  proxy/api/src/http/source.rs
  proxy/api/src/lib.rs
  proxy/api/src/main.rs
Labels: improvement, proxy
