Repository radicle-dev/radicle-upstream, pull requests merged in 2020-09, with the labels that each got.

#841 refactor(ui): keyboard shortcuts modal overhaul
  ui/App.svelte
  ui/DesignSystem/Component/EmptyState.svelte
  ui/DesignSystem/Component/EmptyState/Illustration.svelte
  ui/DesignSystem/Component/Illustration.svelte
  ui/DesignSystem/Component/Shortcuts.svelte
  ui/DesignSystem/Component/index.js
  ui/Hotkeys.svelte
  ui/Screen/Settings.svelte
  ui/Screen/Shortcuts.svelte
  ui/src/illustration.ts
  ui/src/modal.ts
  ui/src/path.ts
Labels: improvement, ui

#839 refactor(ui): profile page
  cypress/integration/project_creation.spec.js
  ui/DesignSystem/Component/Copyable.svelte
  ui/DesignSystem/Component/Header/Large.svelte
  ui/DesignSystem/Component/HorizontalMenu.svelte
  ui/DesignSystem/Component/Urn.svelte
  ui/Screen/Profile.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Profile/ProjectsMenu.svelte
  ui/Screen/Profile/Tracking.svelte
Labels: improvement, ui

#838 feat(proxy): coco announce
  .gitignore
  proxy/Cargo.lock
  proxy/api/Cargo.toml
  proxy/api/src/context.rs
  proxy/api/src/main.rs
  proxy/coco/Cargo.toml
  proxy/coco/src/announcement.rs
  proxy/coco/src/error.rs
  proxy/coco/src/lib.rs
  proxy/coco/src/oid.rs
  proxy/coco/src/peer.rs
Labels: feature, proxy

#859 refactor(proxy): drop warp documentation
  proxy/Cargo.lock
  proxy/api/Cargo.toml
  proxy/api/src/http.rs
  proxy/api/src/http/avatar.rs
  proxy/api/src/http/error.rs
  proxy/api/src/http/identity.rs
  proxy/api/src/http/project.rs
  proxy/api/src/http/session.rs
Labels: dependencies, improvement, proxy

#860 refactor(proxy): move caching out of coco crate
  proxy/Cargo.lock
  proxy/api/src/main.rs
  proxy/api/src/session.rs
  proxy/api/src/session/announcements.rs
  proxy/api/src/session/settings.rs
  proxy/coco/Cargo.toml
  proxy/coco/src/announcement.rs
  proxy/coco/src/error.rs
Labels: improvement, proxy

#861 chore(proxy): remove unnecessary HashMap
  proxy/api/src/project.rs
Labels: improvement, proxy

#856 feat(proxy): fetch project updates
  proxy/coco/src/peer.rs
Labels: feature, proxy

#847 refactor(ui): linting typescript in svelte components
  .buildkite/run.sh
  .eslintrc.js
  .eslintrc.json
  cypress/plugins/index.js
  package.json
  patches/eslint-plugin-svelte3+2.7.3.patch
  svelte.config.js
  ui/DesignSystem/Component/Remote.svelte
  ui/DesignSystem/Primitive/Flex.svelte
  ui/Screen/TransactionDetails.svelte
  ui/src/account.ts
  ui/src/discovery.ts
  ui/src/modal.ts
  ui/src/org.ts
  ui/src/transaction.ts
  yarn.lock
Labels: improvement, ui

#862 chore(proxy): update crate metadata
  proxy/api/Cargo.toml
  proxy/api/src/lib.rs
  proxy/coco/Cargo.toml
  proxy/coco/src/lib.rs
Labels: improvement, proxy

#863 fix(ui): update and fix rollup
  package.json
  rollup.app.js
  rollup.electron.js
  yarn.lock
Labels: dependencies, improvement, ui

#865 feat(proxy): reintroduce notifications
  proxy/api/src/http.rs
  proxy/api/src/http/notification.rs
  proxy/api/src/lib.rs
  proxy/api/src/main.rs
  proxy/api/src/notification.rs
Labels: feature, proxy

#853 refactor(proxy): move Context to use Signer
  proxy/Cargo.lock
  proxy/api/Cargo.toml
  proxy/api/src/context.rs
  proxy/api/src/error.rs
  proxy/api/src/http/control.rs
  proxy/api/src/http/identity.rs
  proxy/api/src/http/project.rs
  proxy/api/src/http/source.rs
  proxy/api/src/identity.rs
  proxy/api/src/lib.rs
  proxy/api/src/main.rs
  proxy/coco/Cargo.toml
  proxy/coco/src/announcement.rs
  proxy/coco/src/control.rs
  proxy/coco/src/keystore.rs
  proxy/coco/src/lib.rs
  proxy/coco/src/peer.rs
  proxy/coco/src/signer.rs
  proxy/coco/src/source.rs
Labels: improvement, proxy

#858 refactor(ui): project creation modal
  cypress/integration/project_creation.spec.js
  ui/App.svelte
  ui/DesignSystem/Component/Illustration.svelte
  ui/DesignSystem/Component/ModalOverlay.svelte
  ui/DesignSystem/Component/RadioOption.svelte
  ui/DesignSystem/Component/RemoteHelperHint.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Input/Directory.svelte
  ui/DesignSystem/Primitive/Input/Text.svelte
  ui/Hotkeys.svelte
  ui/Modal/ProjectCreation.svelte
  ui/Modal/SearchModal.svelte
  ui/Modal/Shortcuts.svelte
  ui/Modal/index.js
  ui/Screen/Profile.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Profile/ProjectsMenu.svelte
  ui/src/illustration.ts
  ui/src/modal.ts
  ui/src/path.ts
  ui/src/screen.ts
Labels: improvement, ui

#874 style(ui): make colors copyable
  .eslintrc.js
  public/colors.css
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/DesignSystemGuide/ColorSwatch.svelte
Labels: improvement, ui

#870 fix(ui): Rollup watch mode work again
  rollup.app.js
Labels: bug, infrastructure, ui

#878 refactor(proxy): prep sync work
  proxy/Cargo.lock
  proxy/api/Cargo.toml
  proxy/api/src/bin/git-remote-rad.rs
  proxy/api/src/context.rs
  proxy/api/src/error.rs
  proxy/api/src/http/control.rs
  proxy/api/src/http/project.rs
  proxy/api/src/http/source.rs
  proxy/api/src/identity.rs
  proxy/api/src/main.rs
  proxy/api/src/node.rs
  proxy/api/src/project.rs
  proxy/api/src/session/announcements.rs
  proxy/coco/Cargo.toml
  proxy/coco/src/identifier.rs
  proxy/coco/src/keystore.rs
  proxy/coco/src/lib.rs
  proxy/coco/src/peer.rs
Labels: improvement, proxy

#879 refactor(proxy): Simplify with_protocol
  proxy/api/src/main.rs
  proxy/coco/src/announcement.rs
  proxy/coco/src/peer.rs
Labels: improvement, proxy

#885 chore(proxy): Run cargo update
  proxy/Cargo.lock
Labels: dependencies, proxy

#875 chore(proxy): integrate ask urn providers
  proxy/Cargo.lock
  proxy/coco/Cargo.toml
  proxy/coco/src/peer.rs
Labels: improvement, proxy

#880 refactor(ui): new project modal validations
  cypress/integration/project_creation.spec.js
  ui/DesignSystem/Primitive/Input/Directory.svelte
  ui/DesignSystem/Primitive/Input/Text.svelte
  ui/Modal/ProjectCreation.svelte
  ui/src/__mocks__/api.ts
  ui/src/project.test.ts
  ui/src/project.ts
  ui/src/source.ts
Labels: improvement, ui

#891 fix(proxy): signed refs retrieval for projects
  proxy/coco/src/announcement.rs
  proxy/coco/src/peer.rs
Labels: bug, proxy

#883 chore(proxy): rustfmt merge_imports
  proxy/.rustfmt.toml
  proxy/api/src/bin/nuke.rs
  proxy/api/src/config.rs
  proxy/api/src/context.rs
  proxy/api/src/http.rs
  proxy/api/src/http/avatar.rs
  proxy/api/src/http/control.rs
  proxy/api/src/http/error.rs
  proxy/api/src/http/identity.rs
  proxy/api/src/http/notification.rs
  proxy/api/src/http/project.rs
  proxy/api/src/http/session.rs
  proxy/api/src/http/source.rs
  proxy/api/src/identity.rs
  proxy/api/src/main.rs
  proxy/api/src/notification.rs
  proxy/api/src/session.rs
  proxy/api/src/session/announcements.rs
  proxy/coco/src/announcement.rs
  proxy/coco/src/config.rs
  proxy/coco/src/control.rs
  proxy/coco/src/error.rs
  proxy/coco/src/git_helper.rs
  proxy/coco/src/identifier.rs
  proxy/coco/src/keystore.rs
  proxy/coco/src/lib.rs
  proxy/coco/src/oid.rs
  proxy/coco/src/peer.rs
  proxy/coco/src/project/checkout.rs
  proxy/coco/src/project/create.rs
  proxy/coco/src/source.rs
Labels: improvement, proxy

#881 refactor(proxy): introduce coco::peer
  proxy/Cargo.lock
  proxy/api/Cargo.toml
  proxy/api/src/context.rs
  proxy/api/src/http.rs
  proxy/api/src/http/control.rs
  proxy/api/src/http/identity.rs
  proxy/api/src/http/project.rs
  proxy/api/src/http/session.rs
  proxy/api/src/http/source.rs
  proxy/api/src/identity.rs
  proxy/api/src/main.rs
  proxy/api/src/project.rs
  proxy/api/src/session.rs
  proxy/api/src/session/announcements.rs
  proxy/coco/Cargo.toml
  proxy/coco/src/announcement.rs
  proxy/coco/src/config.rs
  proxy/coco/src/control.rs
  proxy/coco/src/identifier.rs
  proxy/coco/src/lib.rs
  proxy/coco/src/peer.rs
  proxy/coco/src/peer/announcement.rs
  proxy/coco/src/project/create.rs
  proxy/coco/src/seed.rs
  proxy/coco/src/source.rs
  proxy/coco/src/state.rs
  proxy/coco/src/user.rs
  proxy/coco/tests/common.rs
  proxy/coco/tests/gossip.rs
  proxy/coco/tests/replication.rs
Labels: improvement, proxy

#901 feat(ui): show app version
  native/ipc.js
  native/main.js
  ui/Screen/Settings.svelte
Labels: feature, infrastructure

#897 chore(ui): cleanup
  public/icon.icns
  public/icon.png
  public/icon@2x.png
  ui/DesignSystem/Component/Badge.svelte
Labels: improvement, ui

#892 fix(ui): update copy
  cypress/integration/project_creation.spec.js
  ui/DesignSystem/Component/RemoteHelperHint.svelte
  ui/DesignSystem/Component/TrackToggle.svelte
  ui/Modal/ProjectCreation.svelte
  ui/Modal/SearchModal.svelte
  ui/Screen/Onboarding/EnterName.svelte
  ui/Screen/Onboarding/EnterPassphrase.svelte
  ui/Screen/Project/Untracked.svelte
  ui/Screen/Settings.svelte
  ui/src/project.ts
Labels: improvement, ui

#895 feat(ui): add feedback section in settings
  ui/Screen/Settings.svelte
Labels: improvement, ui

#907 fix(proxy): session not loaded on restart
  proxy/Cargo.lock
  proxy/api/Cargo.toml
  proxy/api/src/session.rs
  proxy/coco/Cargo.toml
  proxy/coco/src/peer/announcement.rs
Labels: bug, proxy

#906 style(ui): cleanup following page
  ui/DesignSystem/Component/ProjectCard.svelte
  ui/DesignSystem/Component/Urn.svelte
  ui/Screen/Profile/Tracking.svelte
  ui/Screen/Settings.svelte
Labels: improvement, ui

#911 chore(release): 0.0.14
  CHANGELOG.md
  package.json
Labels: infrastructure

#913 feat(ui): introduce experimental flag
  DEVELOPMENT.md
  cypress/integration/project_creation.spec.js
  cypress/support/index.js
  native/ipc.js
  native/preload.js
  package.json
  ui/Hotkeys.svelte
  ui/Modal/Shortcuts.svelte
  ui/Screen/Org.svelte
  ui/Screen/Org/Members.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/SourceMenu.svelte
Labels: improvement, ui

#866 feat(proxy): differentiate tracked projects from my projects
  cypress/integration/onboarding.spec.js
  cypress/integration/project_creation.spec.js
  cypress/integration/project_source_browsing.spec.js
  cypress/integration/user_profile.spec.js
  package.json
  proxy/api/src/http/project.rs
  proxy/api/src/project.rs
  proxy/coco/src/error.rs
  ui/Screen/UserProfile/Projects.svelte
  ui/src/__mocks__/api.ts
  ui/src/project.ts
Labels: feature, proxy

#921 fix(ui): allow irc:// as external protocol
  native/main.js
Labels: bug, ui

#914 feat(ui): add input field hint
  ui/DesignSystem/Component/KeyHint.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Input/Password.svelte
  ui/DesignSystem/Primitive/Input/Text.svelte
  ui/Modal/SearchModal.svelte
  ui/Modal/Shortcuts.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Onboarding/EnterName.svelte
  ui/Screen/Onboarding/EnterPassphrase.svelte
Labels: improvement, ui

#931 chore(proxy): avoid building non-release targets
  package.json
Labels: improvement, infrastructure, proxy

#886 refactor(ui): project page
  cypress/integration/project_creation.spec.js
  cypress/integration/project_source_browsing.spec.js
  cypress/integration/user_profile.spec.js
  public/global.css
  ui/DesignSystem/Component/Header/Large.svelte
  ui/DesignSystem/Component/HorizontalMenu.svelte
  ui/DesignSystem/Component/HorizontalMenu/MenuItem.svelte
  ui/DesignSystem/Component/SourceBrowser/File.svelte
  ui/DesignSystem/Component/SourceBrowser/FileSource.svelte
  ui/DesignSystem/Component/SourceBrowser/Folder.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Button.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/CheckoutButton.svelte
  ui/Screen/Project/Commit.svelte
  ui/Screen/Project/Commits.svelte
  ui/Screen/Project/Issues.svelte
  ui/Screen/Project/IssuesMenu.svelte
  ui/Screen/Project/PeerSelector.svelte
  ui/Screen/Project/RevisionsMenu.svelte
  ui/Screen/Project/Source.svelte
  ui/Screen/Project/SourceMenu.svelte
  ui/src/path.ts
  ui/src/source.ts
Labels: improvement, ui

#925 fix(ui): show deleted files in commit view
  ui/Screen/Project/Commit.svelte
Labels: bug, ui

#936 chore(proxy): obliterate nuke binary
  QA.md
  cypress/integration/onboarding.spec.js
  cypress/integration/project_checkout.spec.js
  cypress/integration/project_creation.spec.js
  cypress/integration/project_source_browsing.spec.js
  cypress/integration/routing.spec.js
  cypress/integration/settings_specs.js
  cypress/integration/user_profile.spec.js
  cypress/support/commands.js
  native/main.js
  package.json
  proxy/api/src/bin/nuke.rs
  proxy/api/src/http/control.rs
  proxy/api/src/main.rs
  proxy/coco/src/control.rs
Labels: documentation, improvement, proxy

#922 docs: document release QA procedure
  DEVELOPMENT.md
  QA.md
  cypress/integration/onboarding.spec.js
  cypress/integration/project_checkout.spec.js
  cypress/integration/project_creation.spec.js
  cypress/integration/project_source_browsing.spec.js
  cypress/integration/routing.spec.js
  cypress/integration/settings_specs.js
  cypress/integration/user_profile.spec.js
  cypress/support/commands.js
  native/main.js
  package.json
  proxy/api/src/bin/nuke.rs
  proxy/api/src/http/control.rs
  proxy/api/src/main.rs
  proxy/coco/src/control.rs
  scripts/release.js
Labels: infrastructure

#896 feat(proxy): sync with peers when coming online
  proxy/Cargo.lock
  proxy/api/src/context.rs
  proxy/api/src/http/control.rs
  proxy/api/src/main.rs
  proxy/coco/Cargo.toml
  proxy/coco/src/lib.rs
  proxy/coco/src/peer.rs
  proxy/coco/src/peer/announcement.rs
  proxy/coco/src/peer/run_state.rs
  proxy/coco/src/peer/sync.rs
  proxy/coco/src/state.rs
  proxy/coco/tests/common.rs
  proxy/coco/tests/gossip.rs
  proxy/coco/tests/replication.rs
Labels: feature, proxy

#945 fix(ui): handle repositories with no branches gracefully
  cypress/integration/project_creation.spec.js
  proxy/api/src/http/error.rs
  proxy/coco/src/error.rs
  proxy/coco/src/source.rs
  ui/src/project.ts
Labels: bug, ui

#928 chore(ui): refactor hotkeys
  .eslintrc.js
  ui/DesignSystem/Component/Illustration.svelte
  ui/DesignSystem/Component/KeyHint.svelte
  ui/Hotkeys.svelte
  ui/Modal/Shortcuts.svelte
  ui/src/hotkeys.ts
  ui/src/types/svelte-spa-router/index.d.ts
Labels: improvement, ui

#943 chore(ui): fix ui consistency
  QA.md
  cypress/integration/onboarding.spec.js
  ui/DesignSystem/Component/Header/Large.svelte
  ui/Modal/ProjectCreation.svelte
  ui/Screen/Onboarding/EnterName.svelte
  ui/Screen/Onboarding/Success.svelte
  ui/Screen/Settings.svelte
  ui/src/onboarding.ts
Labels: improvement, ui

#950 chore(docs): improve remote helper hint check docs
  QA.md
Labels: improvement, infrastructure

#938 feat(ui): project name formatting
  cypress/integration/onboarding.spec.js
  cypress/integration/project_creation.spec.js
  ui/DesignSystem/Component/Spinner.svelte
  ui/DesignSystem/Primitive/Button.svelte
  ui/DesignSystem/Primitive/Input/Text.svelte
  ui/Modal/ProjectCreation.svelte
  ui/Screen/Onboarding/EnterName.svelte
  ui/src/onboarding.ts
  ui/src/project.test.ts
  ui/src/project.ts
  ui/src/validation.ts
Labels: improvement, ui

#957 docs(qa): add instructions on how to bypass apple code signing requirements
  QA.md
Labels: infrastructure

#958 chore(release): 0.0.15
  CHANGELOG.md
  package.json
Labels: infrastructure

#903 feat(proxy): waiting room requests
  proxy/Cargo.lock
  proxy/coco/Cargo.toml
  proxy/coco/src/lib.rs
  proxy/coco/src/request.rs
  proxy/coco/src/request/existential.rs
  proxy/coco/src/request/sealed.rs
  proxy/coco/src/request/states.rs
  proxy/coco/src/request/waiting_room.rs
Labels: feature, proxy

#946 feat(proxy): configure include file during checkout
  proxy/Cargo.lock
  proxy/api/src/context.rs
  proxy/api/src/error.rs
  proxy/api/src/http/control.rs
  proxy/api/src/http/error.rs
  proxy/api/src/http/project.rs
  proxy/api/src/main.rs
  proxy/coco/Cargo.toml
  proxy/coco/src/error.rs
  proxy/coco/src/keystore.rs
  proxy/coco/src/lib.rs
  proxy/coco/src/peer/announcement.rs
  proxy/coco/src/project/checkout.rs
  proxy/coco/src/source.rs
  proxy/coco/src/state.rs
  proxy/coco/tests/common.rs
Labels: feature, proxy

#953 fix(ui): improve identity and project name validation
  cypress/integration/onboarding.spec.js
  cypress/integration/project_creation.spec.js
  ui/src/onboarding.ts
  ui/src/project.ts
  ui/src/validation.ts
Labels: improvement, ui

#968 fix(proxy): move delta to config
  proxy/coco/src/request/waiting_room.rs
Labels: improvement, proxy

#962 fix: show commit count on project page
  cypress/integration/project_source_browsing.spec.js
  proxy/api/src/http/source.rs
  proxy/coco/src/source.rs
  ui/DesignSystem/Component/HorizontalMenu.svelte
  ui/DesignSystem/Component/HorizontalMenu/MenuItem.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/Screen/Project.svelte
  ui/Screen/Project/Commits.svelte
  ui/Screen/Project/PeerSelector.svelte
  ui/Screen/Project/Source.svelte
  ui/src/source.ts
Labels: improvement, proxy, ui

#951 chore(ui): typing project creation
  ui/DesignSystem/Component/Dropdown.svelte
  ui/DesignSystem/Component/Dropdown/Option.svelte
  ui/DesignSystem/Component/RadioOption.svelte
  ui/DesignSystem/Component/Tooltip.svelte
  ui/DesignSystem/Primitive/Button.svelte
  ui/DesignSystem/Primitive/Input/Directory.svelte
  ui/Modal/ProjectCreation.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Project/CheckoutButton.svelte
  ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
  ui/src/__mocks__/api.ts
  ui/src/project.test.ts
  ui/src/project.ts
  ui/src/remote.ts
  ui/src/session.test.ts
  ui/src/settings.ts
  ui/src/source.ts
  ui/src/style.ts
Labels: improvement, ui

#944 refactor(proxy): move to coco pooled storage, cancellable async everywhere
  cypress/support/commands.js
  proxy/Cargo.lock
  proxy/api/src/context.rs
  proxy/api/src/http.rs
  proxy/api/src/http/control.rs
  proxy/api/src/http/identity.rs
  proxy/api/src/http/project.rs
  proxy/api/src/http/session.rs
  proxy/api/src/http/source.rs
  proxy/api/src/identity.rs
  proxy/api/src/main.rs
  proxy/api/src/project.rs
  proxy/api/src/session.rs
  proxy/coco/Cargo.toml
  proxy/coco/src/config.rs
  proxy/coco/src/control.rs
  proxy/coco/src/error.rs
  proxy/coco/src/keystore.rs
  proxy/coco/src/lib.rs
  proxy/coco/src/peer.rs
  proxy/coco/src/peer/announcement.rs
  proxy/coco/src/peer/sync.rs
  proxy/coco/src/source.rs
  proxy/coco/src/state.rs
  proxy/coco/tests/common.rs
  proxy/coco/tests/gossip.rs
  proxy/coco/tests/replication.rs
Labels: improvement, proxy

#972 fix(ui): truncate revision selector content
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
Labels: bug, ui

#977 feat(proxy): keep CoCo alive
  proxy/Cargo.lock
  proxy/api/src/main.rs
  proxy/coco/Cargo.toml
  proxy/coco/src/config.rs
Labels: dependencies, feature, proxy

#967 feat(proxy): waiting room subroutine
  proxy/api/src/context.rs
  proxy/api/src/main.rs
  proxy/coco/src/lib.rs
  proxy/coco/src/peer.rs
  proxy/coco/src/peer/request.rs
  proxy/coco/src/peer/run_state.rs
  proxy/coco/src/request.rs
  proxy/coco/src/request/existential.rs
  proxy/coco/src/request/states.rs
  proxy/coco/src/request/waiting_room.rs
  proxy/coco/src/request/waiting_room/stream.rs
  proxy/coco/src/shared.rs
  proxy/coco/tests/common.rs
  proxy/coco/tests/gossip.rs
  proxy/coco/tests/replication.rs
Labels: feature, proxy

#979 fix(proxy): reintroduce sync on startup
  proxy/api/src/main.rs
  proxy/coco/src/peer.rs
  proxy/coco/src/peer/run_state.rs
Labels: bug, proxy

#969 feat(ui): use search bar to kick off project search
  proxy/Cargo.lock
  proxy/api/src/context.rs
  proxy/api/src/http/project.rs
  proxy/api/src/main.rs
  proxy/coco/Cargo.toml
  proxy/coco/src/request.rs
  proxy/coco/src/request/existential.rs
  proxy/coco/src/request/waiting_room.rs
  ui/DesignSystem/Component/TrackToggle.svelte
  ui/Modal/SearchModal.svelte
  ui/Screen/Profile/Tracking.svelte
  ui/src/project.ts
  ui/src/search.ts
  ui/src/waitingRoom.ts
Labels: proxy, ui

#978 docs(qa): advise to use temporary user accounts
  QA.md
  scripts/reset-state.sh
Labels: documentation

#963 fix(ui): only one overlay open at a time
  ui/DesignSystem/Component/AdditionalActionsDropdown.svelte
  ui/DesignSystem/Component/Dropdown.svelte
  ui/DesignSystem/Component/Overlay.svelte
  ui/DesignSystem/Component/SourceBrowser/RevisionSelector.svelte
  ui/DesignSystem/Component/index.js
  ui/Hotkeys.svelte
  ui/Screen/Project/CheckoutButton.svelte
  ui/Screen/Project/PeerSelector.svelte
  ui/src/overlay.test.ts
  ui/src/overlay.ts
Labels: bug, improvement, ui
