Repository radicle-dev/radicle-upstream, pull requests merged in 2020-06, with the labels that each got.

#436 fix(ui): missing revision icon
  ui/Screen/Project.svelte
  ui/Screen/Project/RevisionsMenu.svelte
Labels: bug, ui

#413 feat (ui): unit testing
  .babelrc
  jest.config.js
  package.json
  tsconfig.json
  ui/Screen/Org/MemberRegistration.svelte
  ui/Screen/OrgRegistration.svelte
  ui/src/__mocks__/api.ts
  ui/src/org.test.ts
  ui/src/validation.ts
  yarn.lock
Labels: improvement, ui

#431 feat(ui): include orgId in member registration tx & consolidate wallet logic
  ui/DesignSystem/Component/Transaction.svelte
  ui/Screen/Org/MemberRegistration.svelte
  ui/Screen/OrgRegistration.svelte
  ui/Screen/ProjectRegistration.svelte
  ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
  ui/Screen/UserRegistration/SubmitRegistrationStep.svelte
  ui/src/org.ts
  ui/src/transaction.ts
Labels: improvement, ui

#446 Register member endpoint integration
  cypress/integration/org_member_addition.spec.js
  cypress/support/commands.js
  proxy/src/http/control.rs
  proxy/src/registry.rs
  proxy/src/registry/transaction.rs
  ui/DesignSystem/Component/HorizontalMenu.svelte
  ui/DesignSystem/Component/HorizontalMenu/MenuItem.svelte
  ui/Screen/Org/MemberRegistration.svelte
  ui/Screen/Org/Members.svelte
  ui/src/__mocks__/api.ts
  ui/src/org.test.ts
  ui/src/org.ts
Labels: improvement, ui

#449 fix(proxy): enforce camel case in transaction messages
  proxy/src/registry/transaction.rs
  ui/Screen/ProjectRegistration.svelte
  ui/src/transaction.ts
Labels: proxy

#447 docs: add Linux dev dependencies to docs
  DEVELOPMENT.md
Labels: improvement, infrastructure

#450 chore(proxy): bump registry crate
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/registry.rs
Labels: improvement, proxy

#468 feat(ui): do not allow registering a member twice
  cypress/integration/org_member_addition.spec.js
  ui/Screen/Org/MemberRegistration.svelte
  ui/src/org.ts
  ui/src/transaction.ts
  ui/src/validation.ts
Labels: improvement, ui

#453 feat: user project registration
  proxy/src/http/notification.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/transaction.rs
  proxy/src/registry.rs
  proxy/src/registry/transaction.rs
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/ProjectRegistration.svelte
  ui/src/project.ts
  ui/src/transaction.ts
Labels: feature, proxy, ui

#471 feat: introduce session permissions
  cypress/integration/user_registration.spec.js
  proxy/src/http/session.rs
  proxy/src/session.rs
  ui/Screen/Profile.svelte
  ui/src/session.ts
Labels: improvement, proxy, ui

#457 feat: integrate transaction costs
  cypress/integration/org_member_addition.spec.js
  cypress/integration/org_registration.spec.js
  cypress/integration/project_registration.spec.js
  cypress/integration/user_registration.spec.js
  cypress/support/commands.js
  proxy/src/http.rs
  proxy/src/http/control.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/session.rs
  proxy/src/http/transaction.rs
  proxy/src/http/user.rs
  proxy/src/registry.rs
  proxy/src/registry/transaction.rs
  proxy/src/session.rs
  ui/DesignSystem/Component/Rad.svelte
  ui/DesignSystem/Component/Transaction.svelte
  ui/DesignSystem/Primitive/Numeric.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Org/MemberRegistration.svelte
  ui/Screen/OrgRegistration.svelte
  ui/Screen/ProjectRegistration.svelte
  ui/Screen/TransactionDetails.svelte
  ui/Screen/UserRegistration.svelte
  ui/Screen/UserRegistration/SubmitRegistrationStep.svelte
  ui/src/currency.ts
  ui/src/org.ts
  ui/src/project.ts
  ui/src/session.ts
  ui/src/transaction.ts
  ui/src/user.ts
Labels: feature, proxy, ui

#477 chore(ci): Improve build times
  .buildkite/run.sh
Labels: improvement, infrastructure

#482 fix(proxy): fix transaction subject for project registration
  cypress/integration/project_registration.spec.js
  proxy/src/http/project.rs
  proxy/src/http/transaction.rs
  proxy/src/registry.rs
  proxy/src/registry/transaction.rs
  ui/src/transaction.ts
Labels: bug, proxy, ui

#485 fix(ui): update emojis with full set
  cypress/integration/identity_creation.spec.js
  cypress/integration/org_registration.spec.js
  cypress/integration/project_registration.spec.js
  cypress/integration/user_registration.spec.js
  proxy/src/avatar.rs
  proxy/src/http/avatar.rs
  proxy/src/http/identity.rs
  proxy/src/http/source.rs
Labels: improvement, ui

#414 feat(proxy): coco ascension
  .buildkite/Dockerfile
  .buildkite/pipeline.yaml
  cypress/integration/project_creation.spec.js
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/rust-toolchain
  proxy/src/coco.rs
  proxy/src/coco/source.rs
  proxy/src/error.rs
  proxy/src/http.rs
  proxy/src/http/avatar.rs
  proxy/src/http/control.rs
  proxy/src/http/error.rs
  proxy/src/http/identity.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/session.rs
  proxy/src/http/source.rs
  proxy/src/http/transaction.rs
  proxy/src/http/user.rs
  proxy/src/lib.rs
  proxy/src/main.rs
  proxy/src/project.rs
  proxy/src/registry.rs
  proxy/src/registry/transaction.rs
  ui/Screen/ProjectCreation.svelte
  ui/src/source.ts
Labels: feature, proxy

#490 chore(ci): improve proxy steps
  .buildkite/clippy.sh
  .buildkite/pipeline.yaml
  .buildkite/run.sh
  proxy/src/avatar.rs
  proxy/src/coco.rs
  proxy/src/http.rs
  proxy/src/registry/transaction.rs
Labels: improvement, infrastructure

#472 feat(proxy): option to connect to registry nodes
  DEVELOPMENT.md
  package.json
  proxy/src/main.rs
Labels: feature, proxy

#499 feat(ui): removes display name and avatar url
  cypress/integration/identity_creation.spec.js
  cypress/support/commands.js
  proxy/src/http/identity.rs
  proxy/src/http/source.rs
  proxy/src/identity.rs
  ui/DesignSystem/Component/Sidebar.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/IdentityCreation/Form.svelte
  ui/Screen/IdentityCreation/Success.svelte
  ui/Screen/Profile.svelte
  ui/Screen/ProjectRegistration/RegistrationDetailsStep.svelte
  ui/Screen/UserRegistration/PickHandleStep.svelte
  ui/src/identity.ts
  ui/src/transaction.ts
Labels: improvement, proxy, ui

#489 style(ui): sidebar visual update
  cypress/integration/routing.spec.js
  ui/DesignSystem/Component/Sidebar.svelte
  ui/DesignSystem/Component/Tooltip.svelte
  ui/DesignSystem/Component/index.js
Labels: improvement, ui

#494 style(ui): Profile & Org page update
  cypress/integration/identity_creation.spec.js
  cypress/integration/project_registration.spec.js
  cypress/integration/routing.spec.js
  public/global.css
  ui/DesignSystem/Component/AdditionalActionsDropdown.svelte
  ui/DesignSystem/Component/BigHeader.svelte
  ui/DesignSystem/Component/HorizontalMenu.svelte
  ui/DesignSystem/Component/List.svelte
  ui/DesignSystem/Component/ProjectCard.svelte
  ui/DesignSystem/Component/SidebarLayout.svelte
  ui/DesignSystem/Component/Topbar.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Avatar.svelte
  ui/DesignSystem/Primitive/Icon/Badge.svelte
  ui/DesignSystem/Primitive/Icon/Verified.svelte
  ui/DesignSystem/Primitive/Icon/index.js
  ui/DesignSystem/Primitive/Title.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/IdentityCreation/Success.svelte
  ui/Screen/Org.svelte
  ui/Screen/Org/Fund.svelte
  ui/Screen/Org/Members.svelte
  ui/Screen/Org/Projects.svelte
  ui/Screen/Profile.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Profile/Wallet.svelte
  ui/Screen/Project/Breadcrumb.svelte
  ui/Screen/Project/Issues.svelte
Labels: improvement, ui

#483 feat(ui): restrict register org sidebar button
  cypress/integration/org_registration.spec.js
  ui/DesignSystem/Component/Sidebar.svelte
  ui/DesignSystem/Component/Sidebar/AddOrgButton.svelte
  ui/DesignSystem/Component/SidebarLayout.svelte
Labels: improvement, ui

#498 chore(proxy): Drop duplicated registry types
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/http/control.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/user.rs
  proxy/src/registry.rs
Labels: improvement, proxy

#497 fix(ci): source env file
  .buildkite/clippy.sh
  .buildkite/env.sh
  .buildkite/pipeline.yaml
  .buildkite/run.sh
Labels: bug, infrastructure

#503 chore(ui): fix header scroll behavior
  ui/DesignSystem/Component/BigHeader.svelte
  ui/Screen/Org.svelte
  ui/Screen/Org/Onboard.svelte
  ui/Screen/Profile.svelte
  ui/Screen/Profile/Onboard.svelte
Labels: improvement, ui

#505 chore(ui): align sidebar width & topbar height
  public/global.css
  ui/DesignSystem/Component/List.svelte
  ui/DesignSystem/Component/Sidebar.svelte
  ui/DesignSystem/Component/Sidebar/AddOrgButton.svelte
  ui/DesignSystem/Component/Tooltip.svelte
  ui/DesignSystem/Primitive/Avatar.svelte
  ui/Screen/Project/Commits.svelte
  ui/Screen/Project/Source.svelte
  ui/Screen/Settings.svelte
Labels: improvement, ui

#508 chore(ui): unify layout variables
  public/global.css
  ui/DesignSystem/Component/BigHeader.svelte
  ui/DesignSystem/Component/List.svelte
  ui/Screen/Project/Issue.svelte
  ui/Screen/Project/Issues.svelte
  ui/Screen/Project/Source.svelte
  ui/Screen/Settings.svelte
Labels: improvement, ui

#507 Keystore
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/coco.rs
  proxy/src/coco/config.rs
  proxy/src/error.rs
  proxy/src/keystore.rs
  proxy/src/lib.rs
  proxy/src/main.rs
Labels: dependencies, improvement, proxy

#504 feat: apply project registration permission
  cypress/integration/project_registration.spec.js
  proxy/src/http.rs
  proxy/src/http/identity.rs
  proxy/src/http/session.rs
  proxy/src/session.rs
  ui/Screen/Org.svelte
  ui/Screen/Org/Onboard.svelte
  ui/Screen/Org/Projects.svelte
  ui/Screen/Org/ProjectsMenu.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Project.svelte
Labels: improvement, proxy, ui

#511 feat(proxy): User Creation
  cypress/integration/identity_creation.spec.js
  cypress/integration/routing.spec.js
  cypress/integration/settings_specs.js
  cypress/integration/user_registration.spec.js
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/coco.rs
  proxy/src/error.rs
  proxy/src/http/error.rs
  proxy/src/http/identity.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/session.rs
  proxy/src/http/source.rs
  proxy/src/identity.rs
  proxy/src/project.rs
  proxy/src/registry.rs
  proxy/src/session.rs
  ui/Screen/IdentityCreation.svelte
Labels: feature, improvement, proxy

#525 fix(proxy): add transactionFee to example inputs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/user.rs
Labels: bug, proxy

#522 chore(ui): update Notifications to stack properly
  ui/DesignSystem/Component/Notification.svelte
  ui/DesignSystem/Component/NotificationFaucet.svelte
Labels: bug, improvement, ui

#520 chore(ui): Round of ui fixes
  ui/DesignSystem/Component/AdditionalActionsDropdown.svelte
  ui/DesignSystem/Component/Sidebar.svelte
  ui/DesignSystem/Component/Sidebar/AddOrgButton.svelte
Labels: improvement, ui

#534 chore(ui): bug squashing
  ui/DesignSystem/Component/RadicleLogo.svelte
  ui/DesignSystem/Component/Tooltip.svelte
  ui/DesignSystem/Component/Transaction/Summary.svelte
  ui/DesignSystem/Component/index.js
  ui/Screen/IdentityCreation.svelte
  ui/Screen/OrgRegistration.svelte
  ui/src/transaction.ts
Labels: improvement, ui

#541 chore(proxy): crush build times
  proxy/src/http.rs
  proxy/src/http/avatar.rs
Labels: improvement, infrastructure, proxy

#524 style(ui): add transaction center animations
  ui/App/TransactionCenter.svelte
  ui/DesignSystem/Component/Transaction/Center.svelte
Labels: improvement, ui

#528 feat(proxy): List Entities
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/coco.rs
Labels: improvement, proxy

#537 style(ui): Update empty states
  cypress/integration/org_member_addition.spec.js
  cypress/integration/project_registration.spec.js
  ui/DesignSystem/Component/EmptyState.svelte
  ui/DesignSystem/Component/SidebarLayout.svelte
  ui/DesignSystem/Component/index.js
  ui/DesignSystem/Primitive/Icon/EmptyState.svelte
  ui/DesignSystem/Primitive/Icon/index.js
  ui/Screen/Org/Onboard.svelte
  ui/Screen/Org/Projects.svelte
  ui/Screen/Profile/Onboard.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Project/Issues.svelte
  ui/Screen/Settings.svelte
Labels: feature, improvement, ui

#551 style(ui): Improve profile & org header
  ui/DesignSystem/Component/BigHeader.svelte
  ui/DesignSystem/Component/Copyable.svelte
  ui/DesignSystem/Primitive/Icon/Check.svelte
  ui/DesignSystem/Primitive/Icon/Copy.svelte
  ui/Screen/Profile.svelte
Labels: improvement, ui

#547 chore(ui): add legal section to settings
  ui/Screen/Settings.svelte
Labels: improvement, ui

#552 chore(ui): transparent button background
  ui/DesignSystem/Component/EmptyState.svelte
  ui/DesignSystem/Primitive/Button.svelte
  ui/Screen/Org/Projects.svelte
Labels: improvement, ui

#526 feat: diff integration
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/coco.rs
  proxy/src/coco/source.rs
  proxy/src/http/source.rs
  proxy/src/lib.rs
  ui/DesignSystem/Component/SourceBrowser/FileDiff.svelte
  ui/Screen/Project/Commit.svelte
  ui/src/commitMocks.ts
  ui/src/source.ts
Labels: feature, proxy, ui

#550 Pass registry runtime version explicitly
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/registry.rs
Labels: improvement, proxy

#564 refactor(ui): move all repository browsing state into store
  ui/DesignSystem/Component/SourceBrowser/File.svelte
  ui/DesignSystem/Component/SourceBrowser/Folder.svelte
  ui/Screen/Project/Source.svelte
  ui/src/config.ts
  ui/src/path.ts
  ui/src/source.ts
Labels: improvement, ui

#567 chore(proxy): update librad
  proxy/Cargo.lock
  proxy/Cargo.toml
Labels: dependencies, proxy

#571 style(ui): Improve markdown styling
  ui/DesignSystem/Primitive/Markdown.svelte
Labels: improvement, ui

#523 fix(ui): check id availability in org and user namespaces
  cypress/integration/org_registration.spec.js
  cypress/integration/user_registration.spec.js
  proxy/Cargo.lock
  proxy/Cargo.toml
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/OrgRegistration.svelte
  ui/Screen/UserRegistration/PickHandleStep.svelte
  ui/src/id.ts
  ui/src/org.test.ts
  ui/src/org.ts
  ui/src/validation.ts
Labels: improvement, ui

#580 feat(ui): add back button on commit page
  ui/DesignSystem/Primitive/Icon/ArrowLeft.svelte
  ui/DesignSystem/Primitive/Icon/index.js
  ui/Screen/Project/Commit.svelte
Labels: feature, improvement, ui

#584 fix(ui): color of description text in Settings
  ui/Screen/Settings.svelte
Labels: improvement, ui

#596 feat(proxy): authorized endpoints
  proxy/src/http.rs
  proxy/src/http/control.rs
  proxy/src/http/error.rs
  proxy/src/http/project.rs
Labels: feature, proxy

#586 Update Stats PR
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/coco.rs
  proxy/src/coco/source.rs
  proxy/src/http/control.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/source.rs
  proxy/src/project.rs
Labels: improvement, proxy

#597 refactor(proxy): improve api ergonomics around project registration
  proxy/src/http.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/user.rs
  ui/src/project.ts
Labels: improvement, proxy, ui

#583 style(ui): abstract header as a component
  ui/DesignSystem/Component/Header/Back.svelte
  ui/DesignSystem/Component/Header/Large.svelte
  ui/DesignSystem/Component/Header/index.js
  ui/DesignSystem/Component/index.js
  ui/Screen/Org.svelte
  ui/Screen/Profile.svelte
  ui/Screen/Project/Commit.svelte
  ui/Screen/Project/Issue.svelte
  ui/Screen/Project/Issues.svelte
Labels: improvement, ui

#598 feat(ui): remove application menu-bar
  native/main.js
Labels: feature, ui

#587 refactor(ui): make responsiveness more consistent across pages
  public/global.css
  ui/Screen/Project.svelte
  ui/Screen/Project/Source.svelte
Labels: improvement, ui

#609 chore(proxy): depend on radicle-surf directly
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/coco.rs
  proxy/src/coco/source.rs
  proxy/src/error.rs
  proxy/src/http/error.rs
Labels: improvement, infrastructure, proxy

#608 refactor(proxy): coco peer
  cypress/integration/org_member_addition.spec.js
  cypress/support/commands.js
  proxy/src/coco.rs
  proxy/src/coco/config.rs
  proxy/src/coco/control.rs
  proxy/src/coco/peer.rs
  proxy/src/http.rs
  proxy/src/http/control.rs
  proxy/src/http/identity.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/session.rs
  proxy/src/http/source.rs
  proxy/src/http/user.rs
  proxy/src/identity.rs
  proxy/src/main.rs
  proxy/src/project.rs
  proxy/src/session.rs
Labels: improvement, proxy

#611 fix(ui): remove flicker in source view
  ui/Screen/Project/Commits.svelte
  ui/Screen/Project/Source.svelte
Labels: improvement, ui

#612 feat(proxy): integrate real repo stats
  cypress/integration/project_source_browsing.spec.js
  proxy/src/coco.rs
  proxy/src/coco/peer.rs
  proxy/src/http/control.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/source.rs
  proxy/src/project.rs
  ui/DesignSystem/Component/Stats.svelte
  ui/Screen/DesignSystemGuide.svelte
  ui/Screen/Org/Projects.svelte
  ui/Screen/Profile/Projects.svelte
  ui/Screen/Project/Source.svelte
  ui/src/__mocks__/api.ts
  ui/src/org.test.ts
  ui/src/project.test.ts
  ui/src/project.ts
  ui/src/source.ts
Labels: feature, proxy

#615 fix(ui): fix error display
  ui/DesignSystem/Component/Error.svelte
  ui/DesignSystem/Component/index.js
  ui/Screen/Org/Projects.svelte
  ui/Screen/Profile/Projects.svelte
Labels: bug, ui

#616 chore(proxy): update librad
  proxy/Cargo.lock
  proxy/Cargo.toml
  proxy/src/coco/control.rs
  proxy/src/coco/peer.rs
  proxy/src/coco/source.rs
  proxy/src/http.rs
  proxy/src/http/control.rs
  proxy/src/http/identity.rs
  proxy/src/http/org.rs
  proxy/src/http/project.rs
  proxy/src/http/source.rs
  proxy/src/http/user.rs
  proxy/src/identity.rs
  proxy/src/keystore.rs
  proxy/src/main.rs
Labels: dependencies, proxy

#619 fix(proxy): merge fix
  proxy/src/http/control.rs
  proxy/src/http/project.rs
Labels: bug, proxy
